### ISSUE TITLE
111. Documental - En la hoja de exportación de Excel el área de dependencia, responsable dice es el número de la casilla en lugar de su valor, además en algunos campos dice verdadero/falso. Las últimas columnas no tienen nombres.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#101]
En la hoja de exportación de Excel el área de dependencia, responsable dice es el número de la casilla en lugar de su valor, además en algunos campos dice verdadero/falso. Las últimas columnas no tienen nombres.

**Comment by raulandresduque** [comment]
Los multivalor no se pueden exportar.
Ajustado v0.30, validar

**Comment by julianjposadam** [comment]
La columna de documento a que se refiere, ya que en el formulario no aparece ningún campo para escribir.

**Comment by raulandresduque** [comment]
Es el id del registro, lo dejé sólo como 'Id' para que quede homogéneo con las otras pantallas.
Como comenté arriba los campos multivalor (aquellos que se pueden seleccionar varios valores) no se pueden exportar.

**Comment by julianjposadam** [comment]
La columna E (Documento) sigue apareciendo sin ningún valor y es debido a que no existe ese campo  en el formulario.

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar

**Comment by julianjposadam** [comment]
Falta alinear la etiqueta "Tipo de documento".
