### ISSUE TITLE
119. Ambiental - Investigación de incidentes ambientales - El botón de verificación 'Lesión personal' no inhabilita los campos expuestos en los requerimientos.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#109]
El botón de verificación 'Lesión personal' no inhabilita los campos expuestos en los requerimientos.

**Comment by raulandresduque** [comment]
No tengo el requerimiento, por favor especificar que debe hacerse en este caso

**Comment by julianjposadam** [comment]
Sigue el mismo problema. v0.32

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar
