### ISSUE TITLE
122. Ambiental - Investigación de incidentes ambientales - El botón de verificación 'Otros incidentes' no inhabilita la casilla 'Personas con más control sobre el objeto'.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#112]
El botón de verificación 'Otros incidentes' no inhabilita la casilla 'Personas con más control sobre el objeto'.

**Comment by raulandresduque** [comment]
Según este chequeado o no "Otros Incidentes" se habilita o inhabilita TODA la sección, debe comportarte deferente?
En que momento debe quedar activo "Personas con más control sobre el objeto" de la sección de  "Otros Incidentes" ?

**Comment by julianjposadam** [comment]
Cuando se selecciona otros incidentes debe habilitar TODA la sección y cuando se deselecciona se tiene que inhabilitar TODA la sección. Actualmente si habilita toda la sección, 
![seleccion](https://cloud.githubusercontent.com/assets/19801294/16125457/60ae833e-33b9-11e6-8c93-e955c05ee879.jpg)
pero falta que cuando se deseleccione la casilla bloquee toda la sección incluyendo 'Persona con más control sobre el objeto' que no lo esta haciendo. 
![deseleccion](https://cloud.githubusercontent.com/assets/19801294/16125465/6f0ca406-33b9-11e6-9136-f8101b8c56d9.jpg)

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar
