### ISSUE TITLE
123. Ambiental - Investigación de incidentes ambientales - El botón de guardado dice 'No conformidades'.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#113]
El botón de guardado dice 'No conformidades'.

**Comment by raulandresduque** [comment]
Ajustado v0.30, verificar

**Comment by julianjposadam** [comment]
Tanto el formulario de guardado como el formulario de registro de investigación de incidentes dice es el mismo titulo del formulario de impactos.

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar
