### ISSUE TITLE
129. Ambinetal - Botón indicador - Al generar la consulta por todas las empresas, es decir, dejando vacío el campo cliente, genera el siguiente error creando un bucle infinito, pero genera correctamente el archivo de Excel: (uso no valido de null). /// Al exportar el Excel de todas las empresas lo genera, pero sin ningún valor, todo aparece en ceros, eso quiere decir que no está haciendo la suma de las empresas que están registradas.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#119]
Al generar la consulta por todas las empresas, es decir, dejando vacío el campo cliente, genera el siguiente error creando un bucle infinito, pero genera correctamente el archivo de Excel: (uso no valido de null). /// Al exportar el Excel de todas las empresas lo genera, pero sin ningún valor, todo aparece en ceros, eso quiere decir que no está haciendo la suma de las empresas que están registradas.

**Comment by raulandresduque** [comment]
Ajustado v0.30, validar

**Comment by julianjposadam** [comment]
Al hacer los indicadores el listado de mes no concuerda con los registros, ya que tengo de mayo y junio y en la lista aparece de enero a abril.
