### ISSUE TITLE
22. Accidentalidad - Definir variables obligatorias. 

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#12]
Definir variables obligatorias.

**Comment by raulandresduque** [comment]
Actualmente están Empleado, Fecha de evento, Fecha reporte t fecha investigación.

**Comment by julianjposadam** [comment]
Al momento de importar un accidente, no importa el registro ya que dice que las columnas BQ y BP se encuentran vacías pero el archivo lleva todas las celdas llenas.

**Comment by julianjposadam** [comment]
Al momento de importar un archivo al momento de actualizar los registros sale un error "2473", con el siguiente mensaje.
![errorimportar](https://cloud.githubusercontent.com/assets/19801294/16013517/5ae21dca-3153-11e6-91af-57d7e5c7e46c.jpg)

**Comment by julianjposadam** [comment]
Al importar sigue pidiendo todos los campos como obligatorios, pero al tener los campos llenos sigue diciendo que existen campos vacíos.

**Comment by raulandresduque** [comment]
Se eliminaron validaciones adicionales, tener en cuenta que el archivo no puede tener formato de celdas ni formulas. Si sigue fallando enviar el archivo que se intenta cargar para validarlo.
Validar en v0.33

**Comment by julianjposadam** [comment]
Las validaciones ya son correctas, peor al momento de terminar el proceso de importación sale el error anteriormente mostrado.

**Comment by raulandresduque** [comment]
Por favor copieme el contenido del cuadro de texto donde se va indicando el avance el proceso de importacion justo en el momento que sale el error.

**Comment by julianjposadam** [comment]
Cuando se encuentra actualizando registros.
![cargue-accidentes](https://cloud.githubusercontent.com/assets/19801294/16532407/608785a6-3f97-11e6-8cbb-dc85a79fdebe.jpg)

**Comment by raulandresduque** [comment]
No he encontrado nada raro excepto que se genera un error cuando el costo esta vacio, lo ajuste para que quede en cero en este caso por favor validar. Si vuelve a fallar por favor enviar base de datos y archivo que se intenta cargar. Validar en v0.39

**Comment by copgo** [comment]
Lo probé en runtime y me generó error, otra vez referencia la celda F106. La información la alisté en una nueva plantilla donde lleva desglosados los actos subestándar, las condiciones subestándar, los factores personales y de trabajo. Te adjunto el archivo que intenté cargar.

![error accidentalidad](https://cloud.githubusercontent.com/assets/19764263/16958473/3d4102f8-4da6-11e6-9307-accccc75aa82.png)



[Ejemplo de accidentalidad.xlsx](https://github.com/raulandresduque/SGSST/files/371897/Ejemplo.de.accidentalidad.xlsx)

**Comment by raulandresduque** [comment]
El cargue de accidentalidad no habia sido ajustado con los nuevos campos, validar en v0.42
