### ISSUE TITLE
23. Accidentalidad - Los campos actos y condiciones subestándar, factores personales y de trabajo están apareciendo diligenciados desde el comienzo. 

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#13]
Los campos actos y condiciones subestándar, factores personales y de trabajo están apareciendo diligenciados desde el comienzo.

**Comment by raulandresduque** [comment]
NO me replica, puede ser un error anterior.

**Comment by julianjposadam** [comment]
Al modificar un registro de accidentalidad aparecen estos campos diligenciados sin antes hacerlo.
