### ISSUE TITLE
143. Talento humano - selección - En el reporte de indicadores no están saliendo el nombre de la empresa, el número de requisición ni el cargo solicitado. El número de vacantes y aceptados no debe ir con decimales.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#133]
En el reporte de indicadores no están saliendo el nombre de la empresa, el número de requisición ni el cargo solicitado. El número de vacantes y aceptados no debe ir con decimales.

**Comment by raulandresduque** [comment]
Ajustado v0.31, validar

**Comment by julianjposadam** [comment]
Ahora en el formulario de indicador el mes y año no concuerdan con los registros. Por lo tanto no se puede revisar el archivo del indicador.

**Comment by raulandresduque** [comment]
En proceso estaba mal, se reimplementa
Validar v0.41

**Comment by julianjposadam** [comment]
Antes de abrir el archivo de excel sale el siguiente mensaje 
![seleccion](https://cloud.githubusercontent.com/assets/19801294/17383878/fcd84bf0-599d-11e6-99b3-e871e7af26dd.jpg)
y los indicadores salen en cero

**Comment by raulandresduque** [comment]
Ajustado v0.47, validar
