### ISSUE TITLE
144. Talento humano - selección - En los indicadores de selección no está trayendo bien los datos, pero en los de contratación si trae los vacantes y aceptados bien.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#134]
En los indicadores de selección no está trayendo bien los datos, pero en los de contratación si trae los vacantes y aceptados bien.

**Comment by raulandresduque** [comment]
Por favor enviar el requerimiento y o las indicaciones para verificar

**Comment by copgo** [comment]
Ya te envié los requerimientos y los archivos de Excel que ellos manejan, para que te quede más fácil ver qué hacen los indicadores. Cualquier duda me avisas

**Comment by raulandresduque** [comment]
Ajustado v0.41, validar

**Comment by julianjposadam** [comment]
Las requisiciones no las trae completas, ya que de todas las requisiciones de algunas plantas trae una menos de la que en verdad tiene. La siguiente es la base de datos de ejemplo que uso. 

[SGSST.zip](https://github.com/raulandresduque/SGSST/files/422991/SGSST.zip)

**Comment by raulandresduque** [comment]
Julian, voy a necesitar de mas información porque generé el indicador (año 2016, hasta agosto y todas las empresas) con la DB que me envias y veo que trae TODAS las requisiciones del la id=2 a la id=135, ose todas las que están en la base de datos. Incluyo el reporte generado.
[Indicadores Talento Humano1.xlsx](https://github.com/raulandresduque/SGSST/files/428512/Indicadores.Talento.Humano1.xlsx)

**Comment by julianjposadam** [comment]
Los indicadores los esta calculando incorrecto, ya que no va teniendo en cuenta las requisiciones que ya se les ha registrado una entrevista, y no debería ser así, se tienen en cuenta todas las requisisciones independientemente si tiene entrevista o no.

**Comment by raulandresduque** [comment]
Ajustado v0.51
