### ISSUE TITLE
145. Talento humano - selección - En el indicador de efectividad está tomando mal el numerador, debe ser el índice de eficacia y no el de eficiencia.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#135]
En el indicador de efectividad está tomando mal el numerador, debe ser el índice de eficacia y no el de eficiencia.

**Comment by raulandresduque** [comment]
No entiendo muy bien que esta haciendo el código, creo que tendré que revisar desde el requerimiento, por favor enviarlo.

**Comment by copgo** [comment]
Ya te envié el requerimiento, cualquier duda me avisas

**Comment by raulandresduque** [comment]
Se ajustó, validar en v0,42
