### ISSUE TITLE
148. Talento humano - Contratación - OJO: En el botón de indicadores el formulario dice 'Indicadores ambientales', además está mostrado la misma plantilla de los indicadores de 'Selección'. Faltan todos los indicadores de contratación.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#138]
OJO: En el botón de indicadores el formulario dice 'Indicadores ambientales', además está mostrado la misma plantilla de los indicadores de 'Selección'. Faltan todos los indicadores de contratación.

**Comment by raulandresduque** [comment]
No hay ninguna plantilla cargada para Contratación y el código es el mismo de selección ... hay que implementar esto porque no está, pásame los requerimientos.

**Comment by julianjposadam** [comment]
El formulario de indicadores esta mostrando el mismo de indicadores de selección. Ya que los registros no concuerdan con los de contratación.

**Comment by raulandresduque** [comment]
Como comenté anteriormente, tanto selección como contratación están utilizando el mismo formato y el mismo código entonces es normal que salgan exactamente igual. Tendría que confirmarse con Humberto si hizo esto o definitivamente hay que hacerlo porque no está.

**Comment by copgo** [comment]
Confírmame si con los requerimientos y el archivo que maneja la empresa que te envié, es suficiente, o quieres que te amplíe la explicación para arreglarlo

**Comment by raulandresduque** [comment]
El archivo enviado corresponde al del indicador de selección, no tengo el formato formulado para contratación como se tiene para selección.

**Comment by julianjposadam** [comment]
El siguiente archivo es para que se guíe en los cálculos de los indicadores.
[Datos indicadores.xlsx](https://github.com/raulandresduque/SGSST/files/402631/Datos.indicadores.xlsx)

**Comment by raulandresduque** [comment]
Ajustado v0.48, validar
No había nada de indicador de contratación se hizo desde cero

**Comment by julianjposadam** [comment]
1. Oportunidad de afiliaciones. OK

2. Cumplimiento de documentación: Los indicadores de documentación cuenta raro las respuesta "Si" ya que cada vez que aumenta en uno el si, el indicador en vez de sumarlo lo resta.

3. Cumplimiento de contratación: El numerador es la suma del resultado de los dos anteriores indicadores y el denominador es siempre el número 2.

**Comment by raulandresduque** [comment]
1. OK
2. Ajustado v0.50
3. Así está la fórmula, le adjunto el excel formulado para ver si identifica algún error
[Indicadores Contratacion.xlsx](https://github.com/raulandresduque/SGSST/files/428522/Indicadores.Contratacion.xlsx)
