### ISSUE TITLE
163. Medicina laboral - investigación de enfermedades - La casilla de verificación 'Generó incapacidad' no abre el formulario correspondiente.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#153]
La casilla de verificación 'Generó incapacidad' no abre el formulario correspondiente.

**Comment by raulandresduque** [comment]
Ajustado v0.32, validar

**Comment by julianjposadam** [comment]
Ya abre el formulario, pero sin los datos de la empresa ni el trabajador.

**Comment by raulandresduque** [comment]
Me abre el formulario de ausencias con los datos de la empresa y el trabajador, por favor describir como se reproduce el error.
