### ISSUE TITLE
165. Medicina laboral - investigación de enfermedades - La casilla de verificación de caso médico no se deja seleccionar por lo cual no fue posible probar si abre el formulario correspondiente.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#155]
La casilla de verificación de caso médico no se deja seleccionar por lo cual no fue posible probar si abre el formulario correspondiente.

**Comment by raulandresduque** [comment]
Ajustado v0.32, validar

**Comment by julianjposadam** [comment]
Ya abre el formulario con algunos datos, pero no trae el NIT ni la cédula.
