### ISSUE TITLE
166. Medicina laboral - investigación de enfermedades - Al dar clic en el botón imprimir genera un mensaje de 'archivo no encontrado' aun habiendo registros; también se presenta un bucle infinito. (Archivo no encontrado)

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#156]
Al dar clic en el botón imprimir genera un mensaje de 'archivo no encontrado' aun habiendo registros; también se presenta un bucle infinito. (Archivo no encontrado)

**Comment by raulandresduque** [comment]
Quité el error recurrente pero el reporte requiere de una plantilla llamada "DISEASE_REPORT" que no existe. Busque en lo que me enviaste de Humberto pero no esta ... puedes verificar con él o sino tendría que hacerse esta implementación porque no está.

**Comment by copgo** [comment]
Quedo pendiente que me confirmes si sirvió la plantilla que envío Humberto, gracias

**Comment by raulandresduque** [comment]
Ajustado v0.36, validar.

**Comment by julianjposadam** [comment]
Los datos de la empresa no los coloca en el informe de word cuando se da en el botón imprimir

**Comment by raulandresduque** [comment]
Los datos de la empresa son fijos ya que son los de KW o MANOS respectivamente entonces quedan fijos en el formato, por favor enviarmelos para incluirlos en el formato para las dos empresas

**Comment by copgo** [comment]
Andrés, la parte inicial de este formato es la misma del formato de investigación de accidente de trabajo, si quieres la puedes tomar de ahí

**Comment by raulandresduque** [comment]
Ajustado v0.37, validar

**Comment by julianjposadam** [comment]
El informe no trae la información de "RIESGO QUE POSIBLEMENTE GENERA LA ENFERMEDAD"

**Comment by raulandresduque** [comment]
Ajustado v0,40, validar

**Comment by copgo** [comment]
En el formulario de investigación de enfermedad laboral hay tres campos que están con botón de opción, pero lo correcto es que estén con casilla de verificación, ya que no son mutuamente excluyentes: evaluación médica de ingreso, periódica y específica.

En el reporte salen corridas las empresas de la historia laboral; no muestra la segunda empresa y corre la tercera empresa para ese lugar

![image](https://cloud.githubusercontent.com/assets/19764263/17044924/22babaec-4f8a-11e6-873b-dd2de0226bc2.png)

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar
