### ISSUE TITLE
168. Administración empresa. Actividad económica

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#160]
Al digitar un código de actividad económica en el campo sin abrir el formulario trae solo el nivel de riesgo y no la descripción, y la guarde así (sin descripción). Cuando iba a modificar el código, abrí el formulario y busque el mismo código para traer la descripción y apareció tanto el código de la lista como el que yo cree, es decir esta guardando los códigos que se escriban desde el formulario principal. 
![error_actividadeconomica](https://cloud.githubusercontent.com/assets/19801294/15872397/dadaf982-2cbe-11e6-9e2f-6ea4978fbebd.jpg)

**Comment by raulandresduque** [comment]
Se bloquea campo de código para que sólo pueda ser seleccionada la actividad económica a través de la búsqueda que está diseñada para esto, validar en v0.32
