### ISSUE TITLE
170. Accidentalidad. Informe

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#162]
En el informe sigue apareciendo cliente, cambiar por razón social.

**Comment by raulandresduque** [comment]
Se cambia a Empresa que es lo que se esta manejando en los otros formularios, validad en v0.32

**Comment by julianjposadam** [comment]
Sigue apareciendo cliente y en la consulta aparece NIT cliente.

**Comment by raulandresduque** [comment]
Queda mostrando los dos, NIT empresa y Empresa

**Comment by raulandresduque** [comment]
No estoy entendiendo la solicitud, donde dices que se muestra "NIT empresa y Empresa" ?

**Comment by julianjposadam** [comment]
La idea es cambiar el encabezado que dice "NIT cliente" por "NIT empresa", para que quede los encabezados de forma estándar.

**Comment by raulandresduque** [comment]
Disculpa Julian pero sigo sin identificar donde debe aplicarse el cambio

**Comment by julianjposadam** [comment]
![encabezado](https://cloud.githubusercontent.com/assets/19801294/16494324/8e1df8b8-3eae-11e6-9210-918d020ac982.jpg)

**Comment by raulandresduque** [comment]
Ah ok, estaba era en la consulta, me confundí porque originalmente se estaba hablando era del informe. Validar en v0.38
