### ISSUE TITLE
171. Trabajadores. Registro de historia ocuapcional

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#163]
No se guarda registros de historia ocupacional cuando se esta haciendo el cargue manual de trabajadores.

**Comment by julianjposadam** [comment]
Cuando se carga un archivo para actualizar la historia ocupacional, la herramienta muestra un error '2473'. 
![errorcarguetrb](https://cloud.githubusercontent.com/assets/19801294/15968882/28fb6dbe-2ef3-11e6-8834-6b407a1ad2fe.jpg)

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar
