### ISSUE TITLE
172. Accidentalidad - Generar incapacidad

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#164]
Al momento de seleccionar la casilla de verificación de generar incapacidad, se guarda el registro de ausencia sin necesidad de darle guardar, esto sucede cada vez que se selecciona la casilla de verificación de un registro nuevo o antiguo, generando duplicados de ausencias.

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar

**Comment by julianjposadam** [comment]
Sigue sucediendo el mismo problema, se genera una incapacidad solo con seleccionar la casilla de verificación y sin necesidad de darle guardar.

**Comment by raulandresduque** [comment]
El funcionamiento es ese ya que son dos estructuras diferentes, adicione una confirmación antes de crear, verificar en 0.35
