### ISSUE TITLE
173. Capacitaciones - Alertas

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#165]
Al generar una alerta, la lista de empresas no concuerda con los registros de capacitaciones, así como el informe cuenta y muestra la misma lista de temas para cada empresa seleccionada.

**Comment by raulandresduque** [comment]
Ajustada la lista.
Generé el reporte con diferentes empresas y si cambia la cantidad de temas cuando tiene capacitaciones.

**Comment by julianjposadam** [comment]
Hice un ejemplo de una capacitación del 2015 y dos del 2016, el la alerta debería aparecer sólo el registro de 2015 pero apareció una lista de todas las capacitaciones y sin la fecha.
[Training Alert More Year.pdf](https://github.com/raulandresduque/SGSST/files/326550/Training.Alert.More.Year.pdf)

**Comment by raulandresduque** [comment]
Pensaría que estaría bien que muestre aquellas que nunca se ha hecho capacitación (sin fecha) pero por favor confirma con Patricia si este comportamiento es correcto

**Comment by copgo** [comment]
Por ahora dejémoslo como está y si al entrar en funcionamiento, la empresa dice que no es práctico, lo cambiamos
