### ISSUE TITLE
174. Accidentalidad y enfermedad laboral. Ampliar a 12 el número de investigadores

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#166]
Recuerda que te había dicho que el número de investigadores, tanto para accidente como para enfermedad, pasaba de seis a doce. Te pregunté si era más fácil agregar esos campos o crear subformulario y me dijiste que mejor era agregar los campos

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar
