### ISSUE TITLE
175. Accidentalidad. No guarda registros por formulario

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#167]
En la versión 31 no deja guardar registros de accidentalidad de forma manual (por formulario)

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar

**Comment by julianjposadam** [comment]
En la versión 0.36 sigue sin poder guardar de manera manual un accidente

**Comment by raulandresduque** [comment]
Ajustado v0.37, validar

**Comment by julianjposadam** [comment]
La accidentalidad ya guarda, pero si es posible que se valide con un mensaje como en otros formularios.

**Comment by raulandresduque** [comment]
Ajustado v0.40, validar
