### ISSUE TITLE
177. Talento humano - Selección - Indicadores

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#169]
Al momento de pedir el indicador con o sin empresa muestra un error (3021 - El valor BOF o EOF es True), pero muestra de igual forma el archivo de excel.

**Comment by raulandresduque** [comment]
Este problema se ajustó en una versión anterior sin embargo hay que revisar cómo lo esta construyendo pero eso está en otro incidente, validar en v0.33

**Comment by julianjposadam** [comment]
Al momento de intentar validar el funcionamiento no pudo realizarse, debido a que la lista de año aparece vacía.

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar

**Comment by julianjposadam** [comment]
El titulo del formulario dice "Indicadores ambientales"

**Comment by raulandresduque** [comment]
Ajustado v0.35, validar

**Comment by julianjposadam** [comment]
Muestra el primer error mencionado, además que los registros del archivo de excel no concuerdan con los realmente registrados en la herramienta.

**Comment by julianjposadam** [comment]
Ayer en la reunión de Manos vimos que en aceptados en me de Mayo aparece un 8 y en la hojas data_eficiencia aparecen dos tablas con la misma información siempre.

**Comment by julianjposadam** [comment]
Sucede lo mismo que en indicadores ambientales, es decir que independiente que se pida de una empresa en particular o de todas, sale siempre igual. Ajustar según archivo de Excel enviado como ejemplo. Cualquier duda llamar a Patricia.

**Comment by raulandresduque** [comment]
Ajustado v0.41, validar

**Comment by julianjposadam** [comment]
El error de referencia ya no aparece, pero para los indicadores no esta haciendo el conteo de vacantes y aceptados, por lo que en cada indicador las tablas aparecen en cero.

**Comment by raulandresduque** [comment]
Ajustado v0.48, validar
