### ISSUE TITLE
27. Accidentalidad - Al marcar ¿Generó incapacidad? abre el formulario de ausentismo, pero el campo del documento y cliente no se encuentran protegidos.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#17]
Al marcar ¿Generó incapacidad? abre el formulario de ausentismo, pero el campo del documento y cliente no se encuentran protegidos.

**Comment by raulandresduque** [comment]
Ajustado, verificar

**Comment by julianjposadam** [comment]
Ya aparece bloqueado, pero el número de documento no lo trae.
