### ISSUE TITLE
178. Administración empresas. Cambiar fórmula de aporte a EPS

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#170]
En el módulo Administración / Empresas, hay un subformulario donde se definen los porcentajes que debe asumir Manos o KW y los que debe asumir la empresa cliente en caso de una incapacidad; allí quedan registrados y luego en el módulo Ausentismo, esos datos se utilizan para calcular el costo de la ausencia. En el archivo de Excel que le envié a Diego en su momento, le aclaré que los aportes a Sena y a ICBF sólo se consideraban si el trabajador incapacitado tenía un salario superior a diez mínimos y ya está funcionando así, pero me dijeron que el aporte a EPS también debe cumplir esa condición y yo no lo sabía. Por favor lo incluyes en la formulación

**Comment by raulandresduque** [comment]
Quedó formulado EPS EXACTAMENTE igual que SENA y ICBF considerando el tope de los 10 salarios, validar v0.33
