### ISSUE TITLE
179. Gestión humana - Contratación. Incluir campo Otro

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#171]
En el módulo Gestión humana / Contratación, hay una lista de requisitos y documentos que se deben cumplir, para lo cual se marcan casillas de verificación. Al final falta incluir la casilla "Otro" y el campo de texto "¿Cuál?", que se habilita cuando se marque "Otro"

**Comment by raulandresduque** [comment]
ajustado v0.34, validar
