### ISSUE TITLE
180. Trabajador - Reporte individual

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#172]
En el reporte individual hay cosas por corregir:
1. Salud: faltan los encabezados de fecha, empresa y cada uno de los PVE
2. Dotación: faltan los encabezados de fecha, empresa y epp entregados. Organizar para que quede estándar con el resto del reporte
3. Enfermedad laboral: no muestra nada
4. Accidentalidad: en "Sitio de ocurrencia" está mostrando la variable "Lugar"
5. Ausentismo: arreglar encabezado de "Sistema afectado" ya que la "A" está en mayúscula
6. Medicina laboral: faltan los encabezados de fecha de ingreso a ML, fecha de egreso de ML, Empresa, Tipo de evento y Evento. No está trayendo el evento

**Comment by raulandresduque** [comment]
1. Ajustado en v0.34
2. Ajustado en v0.34
3. Se muestra el ausentismo que sea de origen ENFERMEDAD LABORAL
4. Ajustado en v0.34 (se muestra Sitio del evento)
5. Ajustado en v0.34
6. Ajustado en v0.34

**Comment by copgo** [comment]
El punto 3 no es correcto, debe mostrar todos los registros que tenga el trabajador elegido en enfermedad laboral, independiente que haya originado incapacidad o no. Las variables a traer son: Fecha del reporte, empresa y diagnóstico.

**Comment by raulandresduque** [comment]
Ajustado v0.36, validar.
