### ISSUE TITLE
181. Salud - PVE. Modificar formulario según requerimientos

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#173]
Te envío por correo el documento de requerimientos para que puedas modificar el formulario, porque aunque fue algo que creo que le alcancé a decir a Diego, veo que no está como debe ser (le sobran campos).

**Comment by raulandresduque** [comment]
Podrías por favor hacer referencia a los ajustes que hay que hacer para no hacer una revisión general de el formulario

**Comment by copgo** [comment]
El formulario conserva los campos:
1. No. registro: autonumérico
2. PVE: combo a partir de los nombres de pve creados en el módulo Administración / PVE
3. Empresa: combo a partir de lista creada en el módulo Administración / Empresa
4. Año: número entero de 2016 a 2030
5. Documento PVE: campo para adjuntar documento del programa en pdf
6. Observaciones: campo de texto (tipo memo)
La población objeto y la población cubierta ya no son campos para digitar, sino que la herramienta los debe contar desde el módulo Salud; sin embargo, me parece que no deben quedar en este formulario, por tratarse de una salida; en cambio, se utilizarían en el indicador de pve.
Es decir que todo lo demás se debe retirar (una parte pasa a ser el indicador, como se explica en la siguiente observación)

**Comment by raulandresduque** [comment]
Ajustado v0.39, validar
