### ISSUE TITLE
182. Salud - PVE. Falta salida de indicador

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#174]
Relacionado con el ítem anterior, el indicador de cobertura que aparecía en el formulario de registro, pasa como salida

**Comment by raulandresduque** [comment]
Por favor detallar mejor la solicitud porque no la entiendo

**Comment by copgo** [comment]
Indicador PVE: luego de escoger año, empresa y PVE, mostrar el siguiente indicador. Si se quiere ver el consolidado nacional no se escoge empresa, o si no se escoge PVE, muestra de todos.

Proporción de cobertura:
•	Denominador: Contar automáticamente de módulo Salud / “Carta PVE: Si”, luego de aplicar los filtros elegidos.
•	Numerador: Contar automáticamente de módulo Salud / “Cubierto PVE: Si”, luego de aplicar los filtros elegidos.
•	Fórmula: Dividir numerador entre denominador y multiplicar por 100 el resultado.

**Comment by raulandresduque** [comment]
Es crear una nueva opción o incluir en uno ya existente. Si es nuevo por favor enviar el formato ya que no existe.

**Comment by copgo** [comment]
PVE va a contar con dos indicadores:
1. Proporción de cobertura, que se explica en el ítem 182
2. Proporción de prevalencia, que se explica en el ítem 235

El archivo que genera puede ser por el estilo del que se ha usado en los indicadores de los otros módulos.
Cualquier duda, me avisas

**Comment by raulandresduque** [comment]
Ajustado v0.43, validar
