### ISSUE TITLE
183. Salud - Matriz de riesgos. Arreglos de forma

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#175]
Arreglar el formulario quitando mayúsculas innecesarias y dejándolo con una presentación similar a la de los otros módulos

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar

**Comment by julianjposadam** [comment]
En la pestaña Datos básicos;
        Quitar la mayúscula a "Fuentes", "Medio", "Individuo", 

En la pestaña Niveles:
         "Eliminación", "Sustitución", "Control.."

**Comment by raulandresduque** [comment]
Ajustado v0.37, validar
