### ISSUE TITLE
184. Medicina laboral - Enfermedad laboral. Arreglos de forma al formulario de registro

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#176]
Dentro de los muchos arreglos de forma que hay que hacerle a este formulario, vi que faltaba decirte que coloques un marco llamado "Historia laboral" y dentro colocar las cuatro etiquetas, en lugar de ver cuatro veces "Historia laboral"

**Comment by raulandresduque** [comment]
Ajustado v0.35, validar
