### ISSUE TITLE
185. Talento humano. Permitir cargue masivo de selección y de contratación

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#177]
El módulo de Talento humano necesita aparte de los formularios existentes, la opción de cargue masivo, tanto para "Selección" como para "Contratación". Por favor me indicas el orden de las variables a cargar para hacer la plantilla en Excel de entregar en la empresa

**Comment by raulandresduque** [comment]
Cargue Selección OK
Pendiente cargue Contratación

**Comment by raulandresduque** [comment]
Implementado en version 0.37.
Los campos están en el mismo orden de la exportación a excel, adjunto los ejemplos

**Comment by julianjposadam** [comment]
El cargue masivo de contratación presenta problemas con una validación. 
![cargue contratacion](https://cloud.githubusercontent.com/assets/19801294/16527417/5b5dd85c-3f7c-11e6-8e5c-da6d23361630.jpg)

**Comment by raulandresduque** [comment]
En la imagen se ve un error de valor no válido para ASPIRANTE REMITIDO POR para "Acción comunal" seguramente se trata de espacios en blanco al final, validar
