### ISSUE TITLE
187. Salud - Informe

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#179]
Al intentar generar el informe de salud sale un mensaje de error, por lo cual no lo pude probar. En las versiones anteriores si funcionaba.

![error_infome_salud](https://cloud.githubusercontent.com/assets/19801294/16237725/53156524-37a3-11e6-9688-0fced328bdb0.jpg)

**Comment by raulandresduque** [comment]
Generando tanto sin seleccionar empresa como seleccionado la empresa me genera el reporte sin problemas si se repite tendremos que comprobarlo sobre exactamente la mismas DB

**Comment by copgo** [comment]
En Manos generó bien el informe para todas las empresas, pero dio error cuando se quiso generar para una sola empresa

**Comment by raulandresduque** [comment]
Las pruebas que realizo me genera en los dos casos, por favor enviar la base de datos para probar con la misma información

**Comment by copgo** [comment]
Lo cierro porque aunque no está solucionado, es el mismo ítem 72
