### ISSUE TITLE
188. Salud - Profesiograma

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#180]
Al intentar generar el profesiograma genera error y muestra una ventana para ingresar diferentes valores. 
![profesiograma](https://cloud.githubusercontent.com/assets/19801294/16238092/c906117e-37a4-11e6-9982-22e9c5fcfd5d.jpg)

**Comment by raulandresduque** [comment]
Ajustado v0.35, validar

**Comment by copgo** [comment]
En el reporte falta "Espirometría"

**Comment by raulandresduque** [comment]
Ajustado v0.36, validar.

**Comment by julianjposadam** [comment]
v0.36 sale un nuevo error
![image](https://cloud.githubusercontent.com/assets/19801294/16424465/dcd1181c-3d25-11e6-8c74-fa608fcaa7bf.png)

**Comment by raulandresduque** [comment]
Se estaba grabando el archivo a una ruta especial en "Files" pero local, seguramente te fallo porque no la tenias creada, cambie para que grabe en la carpeta actual de la aplicación, validar en v0.37
