### ISSUE TITLE
189. Medicina laboral (caso medicina laboral) - Pestaña calificación

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#181]
Al momento de seleccionar en una calificación el tipo "PCL" la etiqueta sale encima de la etiqueta de "PVE con el que tiene relación", mientras que el campo para escribir el valor no se ve.

![calificacion_ml](https://cloud.githubusercontent.com/assets/19801294/16238509/54d3652a-37a6-11e6-8318-d140fd0ab1a4.jpg)

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar
