### ISSUE TITLE
190. Medicina laboral - Recomendaciones 

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#182]
Al momento de guardar una recomendación completa muestra un error (7787) seguido del mensaje.

![recomendacion_ml](https://cloud.githubusercontent.com/assets/19801294/16239080/f59d3614-37a8-11e6-9d99-fa1cec17963a.jpg)

El botón de imprimir sólo imprime la primera recomendación independiente de cuál se seleccione.

Una recomendación puede tener varios seguimientos, cosa que no está haciendo ahora, ya que sólo deja un seguimiento por cada recomendación.

**Comment by raulandresduque** [comment]
1. Se ajusta error 7787
2. Ahora imprime la recomendación seleccionada
3. En el requerimiento no dice que una recomendación pueda tener varios seguimientos, por favor validarlo nuevamente ya que el impacto es grande si hay que hacer este ajuste.
Validar en v0.41

**Comment by copgo** [comment]
Efectivamente cada recomendación puede tener más de un seguimiento; en los requerimientos dice:

"Luego de guardar las recomendaciones, colocar botón para hacer seguimiento a recomendaciones.
Subformulario para seguimiento de recomendaciones"

Se pidió subformulario justamente para poder ingresar más de un registro.

Déjalo como no prioritario, ya que como te escribí por Whatsapp, son pocos casos y ahorita no le van a cargar información, pero tocaría arreglarlo después.

**Comment by raulandresduque** [comment]
Hay que hacer un ajuste importante en esta funcionalidad ya que hay que cambiar la estructura de la DB lo que afectará todo el módulo. Queda pendiente.

**Comment by raulandresduque** [comment]
Ajustado v0.47, validar
