### ISSUE TITLE
191. Matriz de riesgo

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#184]
1. No guarda más de dos registros en la matriz de riesgos.
2. En la consulta aparecen casillas de verificación en vez de Si/No y en el archivo de excel la variable rutinario dice Falso/Verdadero en lugar de Si/No.
3. Arreglar la orientación del texto en la columna de la A a la D.
4. Son dos registros y creó una tercera fila de sólo calificaciones
5. En el archivo de excel sobran las tres últimas columnas (tener cuidado de no borrar el código y demás datos del formato)

**Comment by raulandresduque** [comment]
1. Se agregaron tres registros sin problema, si se presenta de nuevo tendría que enviar la DB y los datos que se intentan ingresar para reproducir el problema.
2. Ajustado en una versión anterior
3. No se a qué se refiere con la orientación del texto, es al exportar a excel?
4. No entiendo, en matriz de riesgo no veo nada relacionado con calificaciones. 
5. Las veo bien.

Yo creo que estos temas son muy viejos (21/junio) y ya se han solucionado, por favor revalidar sobre la versión actual

**Comment by copgo** [comment]
1. OK
2. OK
Los puntos siguientes se refieren a la salida que se obtiene al dar clic en Matriz de riesgos; corregir 3 y 4; ignorar el 5

[MATRIZ DE PELIGROS MANOS PLANTA BOGOTA 20151.xlsx](https://github.com/raulandresduque/SGSST/files/382926/MATRIZ.DE.PELIGROS.MANOS.PLANTA.BOGOTA.20151.xlsx)

**Comment by raulandresduque** [comment]
3. Qué orientación debe quedar? Horizontal? Si se deja horizontal aumenta el ancho de las columnas.
4. Pendiente

**Comment by copgo** [comment]
1. Entonces déjalos vertical como están.
2. Pendiente que no salga esa última fila con sólo valoraciones

**Comment by raulandresduque** [comment]
Ajustado v0.47, requiere hacer cambio en la plantilla en base de datos
