### ISSUE TITLE
192. Capacitaciones - Indicadores

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#185]
La gráfica de indicador de cumplimiento en el eje X muestra números en vez de abreviatura de nombres de meses.

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar

**Comment by copgo** [comment]
En la proporción de cobertura sigue mostrando números en lugar de abreviaturas de meses en los rótulos del eje X

![image](https://cloud.githubusercontent.com/assets/19764263/17009754/982407ce-4ec3-11e6-8ad7-cfff6fb0b15b.png)

Los pedí hasta julio pero el encabezado dice que son de enero a diciembre

![image](https://cloud.githubusercontent.com/assets/19764263/17009784/c4d82d54-4ec3-11e6-91e3-c3966eae5cb0.png)


En el formulario en que se definen los parámetros de los indicadores dice "Mes" y no "Mes hasta" como en otros módulos

![image](https://cloud.githubusercontent.com/assets/19764263/17009807/eca12b24-4ec3-11e6-9d1b-d1f490e20907.png)

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar
