### ISSUE TITLE
193. No conformidad - Formato de impresión - Indicador

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#186]
El texto de hallazgo se debe repetir en la descripción.
Aumentar el tamaño de la letra en "Medios documentados"
Corregir "Medios documentado" le falta la s.
Quitar la negrita del texto (no de la etiqueta) de "Mano de obra"  y de "Hallazgo".

En el archivo de indicadores quitar la leyenda de la gráfica, quitar el encabezado de la tabla que dice IF, cambiar "indicadores" por indicador. 
Sobra la columna C (Abiertas); cuenta cerradas y totales únicamente. El indicador se calcula dividiendo cerradas/totales y multiplicando *100.

**Comment by raulandresduque** [comment]
Ajustado v0.39, validar

**Comment by julianjposadam** [comment]
En el libro de indicador, la primera hoja tiene una columna oculta y el título no se ve correctamente cuando se selecciona un empresa específicamente
Corregir "Medios documentado" le falta la s.
Colocar negrita a las etiquetas de los títulos de los cuadros de Análisis causa raíz

**Comment by raulandresduque** [comment]
Ajustado v0.41, validar
