### ISSUE TITLE
194. Talento humano - Contratación - Indicadores

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#187]
El formulario de generar los indicadores de contratación presenta el mismo problema que el formulario de indicadores de selección (lista de año vacía).

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar

**Comment by julianjposadam** [comment]
v0.36 presenta el mismo problema que el indicador de selección.

**Comment by raulandresduque** [comment]
La lista se basa en los datos existentes, si aparece vacio es que no hay datos
