### ISSUE TITLE
196. Ausentismo - Inacapacidades prolongadas

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#189]
El formulario de incapacidades prolongadas tiene mas el titulo dice "reincidentes", debe decir igual que el formulario "Incapacidades prolongadas"
![informe_ausprolongadas](https://cloud.githubusercontent.com/assets/19801294/16312589/107df4bc-393b-11e6-9ec4-895097d313c0.jpg)

**Comment by raulandresduque** [comment]
Ajustado v0.35, validar

**Comment by julianjposadam** [comment]
Falta cambiar en el título "prolongados" por prolongadas

**Comment by raulandresduque** [comment]
Ajustado v0.37, validar
