### ISSUE TITLE
197. Gestión ambienlal - Cinta de opciones - Titulos formularios

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#190]
1. En la cinta de opciones de gestión ambiental, gestión está sin tilde.
2. Reorganizar las etiquetas de la cinta de opciones, ya que sólo aparecen Impacto e Incidente.
![cinta opciones](https://cloud.githubusercontent.com/assets/19801294/16315296/4c9d0a9e-3947-11e6-9bee-d9771ee219f3.jpg)

3. Los títulos de los formularios de cada tema de gestión ambiental dicen "Matriz Impacto Ambiental"
![titulos](https://cloud.githubusercontent.com/assets/19801294/16315303/563c898a-3947-11e6-80e8-6566de106c52.jpg)

**Comment by raulandresduque** [comment]
Ajustado v0.35, validar

**Comment by julianjposadam** [comment]
Falta el título del formulario de guardado de "Registro de consumo y y disposición de residuos" dice "Impacto ambiental"

**Comment by raulandresduque** [comment]
Ajustado v0.37, validar
