### ISSUE TITLE
201. Condiciones de trabajo y salud - Salud - Informe

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#194]
Al momento de intentar crear un informe con o sin empresa seleccionada sale el siguiente mensaje.
![error_infome_salud](https://cloud.githubusercontent.com/assets/19801294/16321331/dab26ff8-3961-11e6-96e7-690f4d3b252b.jpg)

**Comment by raulandresduque** [comment]
Me genera en las dos situaciones bien, similar se ha reportado varias veces pero no me reproduce creo que si sigue el problema nos tocaría probar en conjunto

**Comment by julianjposadam** [comment]
Continua el mismo problema en la v0.36

**Comment by copgo** [comment]
Lo cierro porque aunque no está solucionado, es el mismo ítem 72
