### ISSUE TITLE
202. Ausentismo - Indicadores

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#196]
En los indicadores de ausentismo no tener en cuenta las licencias de maternidad ni paternidad (ni para número de incapacidades ni para días de incapacidad)

**Comment by raulandresduque** [comment]
Ajustado v0.36, validar

**Comment by julianjposadam** [comment]
Los días de incapacidad no cuadran con respecto a los registros.

**Comment by raulandresduque** [comment]
Ajustado v0.38, validar

**Comment by copgo** [comment]
Para el índice de severidad (tanto de ausentismo como de accidentalidad) se pedía en los requerimientos que los días se distribuyeran entre los meses que correspondiera, así: si una persona salía a incapacidad el 20 de enero y le daban 30 días, se tomaban 11 días en enero y el resto en febrero. Eso NO es lo correcto en salud ocupacional y se los dije en la empresa, sin embargo ellos insistieron en calcularlo así. Hoy al hacer muchas pruebas, veo que la herramienta lo está calculando de forma correcta, es decir, contrario a lo que pidió la empresa. ¿En algún momento estuvo como ellos lo pidieron? Te lo asigno para que me digas, pero todavía no le cambies nada.

**Comment by raulandresduque** [comment]
Me parece que cuando estuve revisando esto vi unos cálculos "extraños" y lo dejé más siempre, seguramente aquí se cambio,

**Comment by copgo** [comment]
De acuerdo con lo que hablamos por teléfono, el índice de severidad (tanto de ausentismo como de accidentalidad) debe manejarse diviendo los días en los meses que abarque, tal como está explicado en los requerimientos (deben ser las fórmulas extrañas que viste, porque eso lo alcanzó a hacer Diego).

**Comment by raulandresduque** [comment]
Deje esa parte del cálculo de los días como estaba antes, verificar que funciona de acuerdo a lo requerido.
Validar v0.48
