### ISSUE TITLE
204. Accidentalidad - Hora del evento

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#198]
En un ejemplo que hicimos, colocamos que el accidente ocurrió a las 11:30 y al exportarlo a Excel mostraba que había ocurrido a las 12:00

**Comment by raulandresduque** [comment]
Es raro, este campo NO se estaba exportando en la consulta de accidentalidad entonces no se si lo viste en otra parte, lo agregué en la verisión v.36

**Comment by copgo** [comment]
Entonces fue en la consulta. Listo, gracias, lo revisaremos
