### ISSUE TITLE
205. Administración - Usuario básico

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#199]
Asignamos permiso para el módulo trabajador a un usuario básico, pero al ingresar como ese usuario no muestra habilitado ese módulo

**Comment by raulandresduque** [comment]
Probé nuevamente y me funciona. Agregué unos mensajes de validación que van a aparecer la primera vez que se abra la pestaña de Trabajador, por favor enviarme las pantallas

**Comment by julianjposadam** [comment]
No apareció ningún mensaje, pero funcionó.
