### ISSUE TITLE
4. General - Tipos de datos numéricos y fecha

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#2]
Validar los errores de tipo de datos en los campos numéricos y de fecha para que no muestre el mensaje de error de Access.

**Comment by raulandresduque** [comment]
Por favor indicar los casos específicos.

**Comment by julianjposadam** [comment]
Vigencia de contrato - Administración de empresas.
Los campos numéricos del formulario Administración HHT.
Los campos del formulario Admon salario mínimo. 
Fecha de nacimiento - Administración de trabajadores.
Personas a cargo - Administración de trabajadores.
Salario - Historia ocupacional.
Fecha del evento - Accidentalidad.
Hora del evento - Accidentalidad
Fecha de investigación - Accidentalidad
Costo del accidente - Accidentalidad
Días IT - Accidentalidad.
Días cargados - Accidentalidad
Fecha de inicio - Ausentismo
Duración - Ausentismo
Costo asumido seguridad social - Ausentismo
Fecha pago - Ausentismo
Fecha reincorporación - Ausentismo.
Fecha actualización - Profesiograma.
Fecha - capacitaciones

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar
