### ISSUE TITLE
206. Accidentalidad - Reporte de accidentes sin investigar

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#200]
Probamos dejar un accidente sin investigar, pero al pedir el reporte no lo mostró

**Comment by raulandresduque** [comment]
Probé y me funciono bien, tener en cuenta que para que salga en el reporte:
1. La fecha de investigación debe estar vacía
2. No debe estar cerrado
3. No debe estar objetado
Por favor confirma que se estén cumpliendo estas condiciones
