### ISSUE TITLE
207. Ausentismo - Alerta de trabajadores sin reincorporar

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#201]
Si un trabajador tiene incapacidad hasta fecha actual, no debe aparecer en el listado de trabajadores sin reincorporar (no saldría a partir de "hoy" sino de "mañana")

**Comment by raulandresduque** [comment]
Para este caso no le encontré mucho sentido pedir un rango de fechas, retorna lo que a hoy este pendiente de reincorporar: Fecha incorporación vacía y fecha final de incapacidad < fecha actual.
Coméntame si esta bien.
Validar en v0.36

**Comment by copgo** [comment]
Lo que dices es correcto, pero debe ser que quedó menor o igual a fecha actual, porque en el ejemplo que hicimos el viernes, colocamos que una persona estaba incapacitada ese día (fecha de inicio 24/06/2016, duración 1 día); al pedir el reporte ese día no me la debía mostrar, porque era normal que no tuviera aún fecha de reincorporación, pero si la mostraba.

**Comment by raulandresduque** [comment]
En la versión v0.36 queda ajustado de acuerdo a mis comentario y considerando lo que comentas, validar
