### ISSUE TITLE
209. Salud - Factores de riesgo a los que está expuesto según cargo

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#203]
En el formulario de examen, la segunda pestaña (que es de consulta) debe mostrar los factores de riesgo a los que está expuesto el trabajador según el cargo y la empresa (similar funcionamiento a epp). Actualmente no está mostrando nada.
Debe estar protegida para no dejar modificar las casillas de verificación. Actualmente está bloqueada hasta la barra de desplazamiento vertical.

**Comment by raulandresduque** [comment]
Hice la prueba y siempre y cuando el cargo tenga factores de riesgo los muestra correctamente, por favor confirmar

**Comment by copgo** [comment]
Hasta la versión 35 no lo hacía. Cuando me envíes la versión 36 lo vuelvo a probar
