### ISSUE TITLE
213. Documental - Indicador

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#207]
El indicador está mal, muestra vigentes, divulgados y total (sumando los dos anteriores). Lo correcto es que muestre sólo vigentes y divulgados y divida divulgados/vigentes * 100

**Comment by raulandresduque** [comment]
Ajustado v0.39, validar

**Comment by julianjposadam** [comment]
Sigue mostrando la columna de total v0.40

**Comment by raulandresduque** [comment]
Ajustado v0.41, validar

**Comment by copgo** [comment]
Está corregida la columna que sobraba y la fórmula, pero la gráfica dice "Índice de frecuencia" en lugar de "Indicador de cumplimiento" y en tres partes del archivo de Excel dice "Indicadores" siendo uno solo; por favor dejarlo en singular, lo mismo que el nombre de las dos hojas

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar

**Comment by copgo** [comment]
La segunda hoja sigue en plural "Gráficas"
