### ISSUE TITLE
31. Accidentalidad - Al marcar 'Caso médico' abre el formulario de medicina laboral, pero el campo del documento y cliente no se encuentran protegidos y están sin datos (los combos también aparecen vacíos).

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#21]
Al marcar 'Caso médico' abre el formulario de medicina laboral, pero el campo del documento y cliente no se encuentran protegidos y están sin datos (los combos también aparecen vacíos).

**Comment by raulandresduque** [comment]
Ajustado, verificar

**Comment by julianjposadam** [comment]
Los campos ya se encuentran protegidos, pero el documento aparece limpio.
