### ISSUE TITLE
216. Incluir logos de Liberty y PC al inicio

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#210]
Al entrar a la aplicación, mostrar logos de Liberty y PC. Pendiente envío de los mismos

**Comment by copgo** [comment]
Envío logos
![logo liberty](https://cloud.githubusercontent.com/assets/19764263/16359238/4b58f63c-3af2-11e6-9b4e-9cf519ca0463.png)
![logo pc alta resolucion](https://cloud.githubusercontent.com/assets/19764263/16359240/60076db6-3af2-11e6-8122-ddc229fec810.png)

**Comment by raulandresduque** [comment]
Ajustado v0.36, validar

**Comment by julianjposadam** [comment]
Ajustar el tamaño de las imágenes, para que el de PC sea el más pequeño y el de Liberty sea el más grande.

**Comment by raulandresduque** [comment]
Ajustado v0.37, validar

**Comment by copgo** [comment]
Falta la tilde de "asesoría"

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar
