### ISSUE TITLE
217. General - Agregar valor a listas de combos

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#211]
1. Agregar "Sin dato" a escolaridad, estado civil, estrato, tipo de vivienda y raza.
2. Agregar "Listado" a bancos.
3. Agregar "Pensionado" a AFP
4. En código CIE (utilizado en módulo ausentismo y en investigación de enfermedad laboral) incluir opción 999: diagnostico sin dato, sistema afectado: sin dato.

**Comment by raulandresduque** [comment]
Ajustado v0.38, validar
