### ISSUE TITLE
218. Trabajador - Historia ocupacional

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#212]
Al probar en Manos no guardó historia ocupacional, por lo que no se pudieron probar cosas de otros módulos.

**Comment by raulandresduque** [comment]
Hice varias pruebas y me funcionó, por favor enviar pantalla con los datos que se están diligenciando

**Comment by julianjposadam** [comment]
En las pruebas que se hicieron en la oficina el historial guardó sin problemas, por lo tanto no le puedo adjuntar ninguna captura. La próxima ocasión que se se hagan pruebas en Manos con la ultima versión, se confirmará si se solucionó el problema.

**Comment by raulandresduque** [comment]
Ok, por favor me lo asigna cuando tenga evidencias adicionales. Por otro issue se hicieron unos ajustes en esta parte entonces es muy posible que ya este funcionando, validar en v0.39
