### ISSUE TITLE
223. Gestión ambiental - Indicadores

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#217]
Independiente que los indicadores se pidan para una empresa en particular o para todas las empresas, la salida siempre es la misma. Para cada uno de los indicadores está mostrando doble tabla y doble gráfica, en teoría una de la empresa elegida y una en general, lo cual no es necesario. Por favor eliminar las columnas F, G, H y segunda gráfica en todos los indicadores.

**Comment by raulandresduque** [comment]
Ajustado v0.41, validar

**Comment by copgo** [comment]
Por favor cambiar los encabezados del indicador de cumplimiento de requisitos legales, así:

"Existencia" cambia por "Requisitos que aplican"
"Existencia + cumplimiento legal" cambia por "Requisitos cumplidos"

![image](https://cloud.githubusercontent.com/assets/19764263/17045090/1495f56a-4f8c-11e6-8e72-196c46f8e1a7.png)

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar

**Comment by copgo** [comment]
No lo pude probar porque al querer pedir los indicadores, no me mostró nada en el combo de año. Digité "2016" pero me mostró error

![image](https://cloud.githubusercontent.com/assets/19764263/17122069/20204736-529e-11e6-8614-0c7dbc9d9f64.png)

**Comment by raulandresduque** [comment]
- La lista de años la basa en los años de las investigaciones de incidentes existentes, si no hay datos no muestra nada
- La lista de empresas la basa en las empresa de los Consumos que se hayan registrado, si no hay datos no muestra nada.

Validar si lo de arriba esta bien o debe modificarse

**Comment by copgo** [comment]
La lista de empresas si la debe basar en la de empresas que tengan consumos, pero la de años también debería basarla en los consumos registrados

**Comment by raulandresduque** [comment]
Ajustado v0.43, validar
