### ISSUE TITLE
224. Talento humano - Selección

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#218]
1. Validar fecha de aceptación >= a fecha entrevista. Actualmente sólo acepta mayor.
2. Está dejando que un usuario básico cancele una requisición, siendo éste un privilegio del administrador.

**Comment by raulandresduque** [comment]
Ajustado v0.39, validar

**Comment by julianjposadam** [comment]
1. En la versión 0.41 la fecha sigue sin estar validada.
2. Ahora un usuario básico no puede ingresar al módulo de talento humano. El usuario básico si tiene que poder ingresar al módulo, pero que no pueda cancelar una requisición.

**Comment by raulandresduque** [comment]
El usuario básico no activa el módulo de talento humano porque está inactivo en administración del usuario, puede crear otro usuario dandole permisos o usar **usuprueba**. 
Ajustado v0.42, validar
