### ISSUE TITLE
226. Talento humano - Contratación

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#220]
1. Poder buscar empresa por nombre y no sólo por NIT (dejar igual a como se maneja en otros módulos)
2. Los campos de información del trabajador no se traen a partir de la cédula si no digitar o elegir según sea el caso. La cédula no debe ser un combo si no un campo de texto libre que acepte cualquier valor.

**Comment by raulandresduque** [comment]
Intenté realizar el cargue desde el último archivo de manos pero esta incompleto, no tiene el NIT entonces la aplicación lo toma como filas vacías y por eso no carga nada, intenté realizar el cruce con los nombre de las empresas pero no están completos, se debe ajustar el archivo antes de intentar un cargue.
Validar los otros puntos en v0.41

**Comment by julianjposadam** [comment]
Al momento de importar la columna "INDUCCIÓN Y ENTREGA DE CARTILLA" los valores son de SI y NO pero la herramienta no importa los registros. 
![error cargue contratacion](https://cloud.githubusercontent.com/assets/19801294/16968580/5fee36d4-4dd5-11e6-99f9-1f09e5c822cd.jpg)

El archivo es el siguiente. 
[Datos Manos.xlsx](https://github.com/raulandresduque/SGSST/files/372559/Datos.Manos.xlsx)

**Comment by julianjposadam** [comment]
1. Ya está bien
2. Todavía tiene el combo, debería ser un campo de texto

**Comment by raulandresduque** [comment]
El combo cumple también la función de cuadro de texto con la ventaja que autocompletar

**Comment by julianjposadam** [comment]
Si, pero la idea es que el campo se autocomplete cuando se le escribe no sólo el NIT sino que también funcione con el nombre de la empresa.
