### ISSUE TITLE
227. Plan de acción

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#221]
1. En el formulario falta proteger fecha de asignación y cambiar status por estado 
2. En la consulta eliminar "Módulo" y "meta" 
3. El título del formulario de actividades dice "Registro de ausencias al trabajo" 
4. Si se cancela un plan no muestra en estado "Cancelada" 
5. Está dejando que un usuario básico cancele un plan de acción, siendo éste un privilegio del administrador.

**Comment by raulandresduque** [comment]
Ajustado v0.41, validar

**Comment by copgo** [comment]
1. Cuando se abre el formulario para ingresar actividades aparece plazo 3 días
2. Lo probé como usuario básico y seguía desprotegida la fecha de asignación y me dejó cancelar la actividad

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar
