### ISSUE TITLE
229. Accidentalidad - Cargue masivo

### ISSUE THREAD

**Issue by julianjposadam** [raulandresduque/SGSST#223]
Ajustar el cargue masivo de accidentalidad con respecto a la plantilla

[Plantilla empresas v2_06072016.zip](https://github.com/raulandresduque/SGSST/files/351028/Plantilla.empresas.v2_06072016.zip)

**Comment by julianjposadam** [comment]
Al momento de hacer un cargue masivo aparece un nuevo error 

![errorimport_accidentes](https://cloud.githubusercontent.com/assets/19801294/16879008/4a408ad0-4a74-11e6-9e05-20c0633d1f09.jpg)

**Comment by copgo** [comment]
Lo cierro porque aunque no funciona, ya está en el ítem 22
