### ISSUE TITLE
230. Administración - Matriz de riesgos y epp por cargo - Autoajustar texto

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#224]
En el formulario de Administración / Matriz de riesgos y epp por cargo, los dos subformularios no permiten leer el texto completo cuando es largo, por favor ampliarlo (horizontal o verticalmente)

**Comment by copgo** [comment]
En ese mismo formulario permitir la opción de "No aplica" para epp; puede ser con casilla de verificación como hablamos esta mañana o como te parezca que quede mejor. Lo importante es que se vea que si ningún epp está seleccionado, no es por olvido de la digitadora

**Comment by raulandresduque** [comment]
Ajustado v0.41, validar
