### ISSUE TITLE
233. General - Ordenar empresas alfabéticamente

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#227]
En los combos donde se elige empresa en cualquier módulo, dejar la lista ordenada alfabéticamente

**Comment by raulandresduque** [comment]
Se ajusta en los formularios identificados si se identifica alguno faltante por favor reportarlo
Validar v0.41

**Comment by copgo** [comment]
Ya está bien en la mayoría de formularios, falta en:
1. Formulario informe accidentalidad
2. Formularios de alerta de ausentismo (3)

Revisándolo vi que el formulario de ausentismo dice "Cliente" en lugar de "Empresa"

![image](https://cloud.githubusercontent.com/assets/19764263/17038626/3c5f913a-4f5c-11e6-99e8-38a081e1ecd7.png)

En  la consulta de PVE también

![image](https://cloud.githubusercontent.com/assets/19764263/17038660/64999be6-4f5c-11e6-96bc-67a9fc9549ae.png)

En el formulario para pedir alerta de capacitación también

![image](https://cloud.githubusercontent.com/assets/19764263/17039018/178aa9ba-4f5e-11e6-837e-df7b84d1e425.png)

En el formulario para pedir alerta de tareas pendientes también

![image](https://cloud.githubusercontent.com/assets/19764263/17039076/6045ca86-4f5e-11e6-92d7-760608802fb5.png)


El formulario de No conformidad dice "Empresal", le sobra una ele al final

![image](https://cloud.githubusercontent.com/assets/19764263/17038783/f7cdee6c-4f5c-11e6-8ced-8e85802adb70.png)

**Comment by raulandresduque** [comment]
Ajustadp v0.42, validar

**Comment by copgo** [comment]
Falta ordenar las empresas en la segunda alerta de ausentismo

![image](https://cloud.githubusercontent.com/assets/19764263/17121870/32932e12-529c-11e6-88e4-c4a9b3f48a3b.png)

**Comment by raulandresduque** [comment]
Ajustado v0.43, validar

**Comment by julianjposadam** [comment]
Informe de salud 
![informe salud](https://cloud.githubusercontent.com/assets/19801294/17344061/6576a216-58c6-11e6-9c84-02ec3ee9e629.jpg)

**Comment by raulandresduque** [comment]
Ajustado v0.47, validar

**Comment by julianjposadam** [comment]
Falta esta lista las demás se encuentran bien 
![orden](https://cloud.githubusercontent.com/assets/19801294/17497739/09be4b64-5d89-11e6-9e04-5ca4091ceb1d.png)

**Comment by raulandresduque** [comment]
Ajustado v0.48, validar
