### ISSUE TITLE
235. Salud - PVE- Indicador de prevalencia

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#229]
En el módulo Salud / PVE, existe un indicador de cobertura, ahora falta incluir un indicador de prevalencia, de la siguiente forma:
Nombre: Proporción de prevalencia de alteraciones relacionadas con PVE
Fórmula: No. de registros con "Vigilancia alta" afirmativa / No. de registros con "Carta PVE" afirmativa * 100
Tener en cuenta el mismo período de tiempo del indicador de cobertura (de hecho el denominador es el mismo).
Para garantizar que no haya errores de digitación que lo afecten, cuando "Vigilancia alta " sea afirmativo, automáticamente "Carta PVE" debe quedar afirmativo (tanto para ingreso manual como para cargue  masivo)

**Comment by raulandresduque** [comment]
Para Salud / PVE no veo que exista un indicador, por favor indícame a cual se refiere

**Comment by copgo** [comment]
El indicador de cobertura que se menciona como primer indicador de PVE es el que se dice en el ítem 182, así que te lo aclaro allá

**Comment by copgo** [comment]
Lo cerré por error, porque el ítem 182 es el indicador de cobertura y el ítem 235 es el indicador de prevalencia

**Comment by raulandresduque** [comment]
Ajustado v0.43, validar

**Comment by copgo** [comment]
El indicador está bien pero vi que cuando se exporta a Excel, el encabezado no dice "Vigilancia alta" sino "Vigencia"

**Comment by raulandresduque** [comment]
Disculpa, no entiendo a qué se refiere exportar a excel ya que el indicador ya es un archivo excel.

**Comment by copgo** [comment]
Qué pena, revolví temas. Lo que pasa es que el indicador está bien, pero aparte de eso, cuando se exporta a Excel la información registrada en lugar de "Vigilancia alta" dice "Vigencia"

**Comment by raulandresduque** [comment]
Disculpa pero sigo sin entender ...
Voy a Salud - PVE y exporto  a excel y no hay niguna columna con el nombre "Vigencia", estas hablando de otra opción diferente a Salud - PVE que es la que se esta hablando en este isssue?

**Comment by copgo** [comment]
La información que se exporta es la de Salud. Disculpa, lo que sucede es que como de ahí sale el indicador de prevalencia, lo vi en ese momento y te lo escribí

**Comment by raulandresduque** [comment]
Ajustado v0.47, validar
