### ISSUE TITLE
33. Accidentalidad - Al dar clic en el botón 'Crear plan de acción' abre el formulario, pero no aparece el origen seleccionado y protegido. Vi que agregaste un campo 'Módulo', pero la idea era que en este caso mostrara en Origen: 'Investigación de incidente/accidente'. 

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#23]
Al dar clic en el botón 'Crear plan de acción' abre el formulario, pero no aparece el origen seleccionado y protegido. Vi que agregaste un campo 'Módulo', pero la idea era que en este caso mostrara en Origen: 'Investigación de incidente/accidente'.

**Comment by raulandresduque** [comment]
Hice lo mismo para los otros módulos pero tienes que revisar la equivalencia Módulo del que se llama vs Origen

**Comment by julianjposadam** [comment]
Ya funciona bien el combo, pero seria bueno si se puede alargar un poco más el tamaño del combo para que no se vea cortada la palabra.
