### ISSUE TITLE
238. Vincular planes de acción a reportes - Prioritario

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#232]
Falta vincular los planes de acción a los reportes de accidente, enfermedad y no conformidades, según formatos de la empresa establecidos desde el principio

**Comment by raulandresduque** [comment]
1. En accidente identifico donde se incluye
2. En ausentismo no identifico reporte donde se deba incluir
3. EN no conformidades el reporte tiene una sección de acciones correctivas y otra de acciones preventivas, supongo que aquí sería donde se incluyen los planes de acción, pero cómo determinar si son preventivas o correctivas?

Como te comentaba para los formatos word debemos definir un máximo de tareas, estaría bien 5?

**Comment by copgo** [comment]
1. OK
2. No es en ausentismo sino en investigación de enfermedad laboral, que tiene un formato muy parecido al de accidente de trabajo
3. Déjalas en acciones correctivas, por favor.

Listo, en Word deja cinco tareas como máximo

**Comment by raulandresduque** [comment]
Ajustado v0.46, validar
