### ISSUE TITLE
239. Salud - Factores de riesgo en pestaña de lectura

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#233]
Siguen sin verse los factores de riesgo a los que está expuesta una persona según el cargo y la empresa en la que trabaja

**Comment by raulandresduque** [comment]
Me funciona correctamente, adjunto imágenes de factor de riesgo y de salud

![matriz](https://cloud.githubusercontent.com/assets/1543644/16913658/a7911800-4cb1-11e6-8294-a5ef4ff47a27.png)
![salud1](https://cloud.githubusercontent.com/assets/1543644/16913657/a78f057e-4cb1-11e6-90fe-874f3e638a0c.png)
![salud2](https://cloud.githubusercontent.com/assets/1543644/16913656/a78eb326-4cb1-11e6-8aa1-46e7d32b7ad9.png)

**Comment by copgo** [comment]
En Access me funcionó bien, mañana lo reviso en runtime

**Comment by copgo** [comment]
Ya funciona bien en runtime también, pero vi algo raro con los riesgos. Primero en la matriz de riesgos por cargo, me muestra unos de seguridad como si fueran psicosociales, a pesar que en no está así en la clasificación de los factores de riesgo del módulo Administración.

![image](https://cloud.githubusercontent.com/assets/19764263/16996282/2f8fbab6-4e76-11e6-9a28-fce7060fe83f.png)

Y segundo, en el módulo de condiciones de trabajo y salud, repite el riesgo tecnológico

![image](https://cloud.githubusercontent.com/assets/19764263/16996306/4fa33d78-4e76-11e6-92bf-315f973abf11.png)

**Comment by raulandresduque** [comment]
Los dos corresponden a información incorrecta que seguramente hice a mano ya que por la aplicación no es posible

**Comment by copgo** [comment]
Siendo así, queda cerrado
