### ISSUE TITLE
240. Administración - Usuarios

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#234]
Retirar todos los mensajes de validación que colocaste. Ya funcionó bien.

![image](https://cloud.githubusercontent.com/assets/19764263/17031546/53dc20a2-4f3a-11e6-8685-56a52eae78e9.png)

![image](https://cloud.githubusercontent.com/assets/19764263/17031550/5a4688d8-4f3a-11e6-9232-768101137469.png)

![image](https://cloud.githubusercontent.com/assets/19764263/17031555/60487af2-4f3a-11e6-8de8-d3d9705e95db.png)

![image](https://cloud.githubusercontent.com/assets/19764263/17031558/663420ba-4f3a-11e6-90ea-82ad2724df19.png)

![image](https://cloud.githubusercontent.com/assets/19764263/17031563/6c786b02-4f3a-11e6-9b61-84f6990664ca.png)

![image](https://cloud.githubusercontent.com/assets/19764263/17031571/73a18b2a-4f3a-11e6-820e-dfc19ff04892.png)

![image](https://cloud.githubusercontent.com/assets/19764263/17031580/79461c62-4f3a-11e6-945d-4e7c602594c3.png)

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar
