### ISSUE TITLE
241. No conformidades - reporte para imprimir

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#235]
El reporte de no conformidades está saliendo con varios errores, ya que no muestra los campos diligenciados con lo que se registró, sino con "X", o lo de un campo en otro. Adicionalmente no está mostrando los planes de acción que tiene vinculados

**Comment by raulandresduque** [comment]
Ajustado el tema de los "XX". 
Los planes de acción esta pendiente ya del item 238
Validar en v0.45
