### ISSUE TITLE
242. Talento humano - Importar contratación

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#236]
1. No pudimos importar contratación porque dice que algunos trabajadores no tienen historia en esa fecha, ¿es posible quitar la validación igual que hiciste en salud?

2. Por favor en quién lo recomienda, cambia "Empresa usuaria / empresa cliente" por "Empresa usuaria"

**Comment by raulandresduque** [comment]
Ajustado v0.45, sin embargo hay mucho errores por empleados que no tienen historia en la empresa y los valores de "ACCIÓN COMUNAL" no tienen la tilde. También para "ASPIRANTE REMITIDO POR" hay valores "MANOS" que no es válido, debería ser "EMPRESA"

**Comment by copgo** [comment]
Si vi y ya lo corregí (en el archivo que te envié para probar lo de salud, ya está corregido. Falta cambiar la nueva categoría de "Empresa usuaria" y mañana lo pruebo en la nueva versión.

**Comment by copgo** [comment]
Pudimos hacer el cargue pero sacando muchos registros que decía que no tenían historia en esa fecha. Al revisar los casos, pasaban cosas como que entró a trabajar el 06/01/2016 y la afiliación a ARL la hicieron el 05/01/2016. Mañana vuelvo a preguntar para saber si retiras las validaciones de fecha

**Comment by copgo** [comment]
En la empresa me dijeron que si se puede dar el caso de hacer afiliaciones fuera del rango de fechas en que esté trabajando, por lo que si es necesario dejarlo sin validaciones de fecha, igual que se hizo en Salud

**Comment by raulandresduque** [comment]
Esto ya estaba ajustado cuando se hizo el cambio en Salud, validar v0.47

**Comment by copgo** [comment]
Pero como te decía en el comentario, luego de corregir errores de forma, no nos dejaba cargar los trabajadores que tenían la afiliación a EPS o AFP un día antes del contrato y nos tocó retirarlos del archivo para poderlos cargar. Por favor revisas que si hayas quitado todas las validaciones y me envías este módulo vacío para cargar ahora si completos los registros que me entregaron. Gracias

**Comment by raulandresduque** [comment]
Realice un ajuste que faltaba en la v0.47 pero igual hay errores en el archivo:

* 4 empleados que no tienen ninguna historia para esa empresa
Fila: 44 Columna: C-Documento del trabajado - Empleado no tiene historia para esta empresa (74849682, 8001879743)
Fila: 125 Columna: C-Documento del trabajado - Empleado no tiene historia para esta empresa (1073234712, 8600066569)
Fila: 210 Columna: C-Documento del trabajado - Empleado no tiene historia para esta empresa (97436156, 9000890054)
Fila: 294 Columna: C-Documento del trabajado - Empleado no tiene historia para esta empresa (79819153, 8600066569)

* Muchos valores inválidos de ASPIRANTE REMITIDO POR (EMPRESA USUARIA / EMPRESA CLIENTE)

Deje vacío el módulo

**Comment by julianjposadam** [comment]
Al intentar importar el archivo, sale un mensaje aún teniendo todos los campos llenos.
![mensaje](https://cloud.githubusercontent.com/assets/19801294/17497797/42626658-5d89-11e6-8657-ddf90d4d517a.png)

**Comment by raulandresduque** [comment]
Por favor enviar el archivo que intenta cargar

**Comment by julianjposadam** [comment]
[Plantilla contratación.xlsx](https://github.com/raulandresduque/SGSST/files/409068/Plantilla.contratacion.xlsx)

**Comment by raulandresduque** [comment]
Ajustado v0.48, sin embargo se identifica que hay empleados con la misma empresa dos o más veces y ya como no se esta haciendo control por fecha no hay forma de relacionarlos con la historia, por lo tanto sólo se carga uno de ellos y se informa el documento para ser analizado el caso y digitado a mano. En una operación normal no debe haber problemas porque va tomar la última historia con esa empresa
