### ISSUE TITLE
243. Trabajadores - Reporte individual

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#237]
Al pedir el reporte individual del trabajador Óscar Javier Julio Meneses, cédula 1001059112, muestra un registro en enfermedad laboral que no existe (está repitiendo información).

Luego pedimos el reporte del trabajador Yefry Danilo Rodríguez Gamboa, cédula 1073600616 y también mostró registros en enfermedad laboral que no existen.

**Comment by raulandresduque** [comment]
Ajustado v0.45
