### ISSUE TITLE
244. Accidentalidad - Consulta e informe

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#238]
La consulta de accidentalidad no está actualizada con las columnas nuevas de actos subestándar, condiciones subestándar, factores personales y factores de trabajo. De igual forma al exportar a Excel o pedir el informe, no está mostrando completas esas variables.

**Comment by raulandresduque** [comment]
Si se muestran actos subestándar, condiciones subestándar, factores personales y factores de trabajo tanto en la consulta como al exportar.

**Comment by copgo** [comment]
Pensé que iba a quedar dividido en varias columnas, pero ya vi que las concatenaste en una sola
