### ISSUE TITLE
34. Accidentalidad - El botón 'Cerrar investigación' bloquea los campos momentáneamente, pero cuando un usuario básico ingresa los encuentra desbloqueados.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#24]
El botón 'Cerrar investigación' bloquea los campos momentáneamente, pero cuando un usuario básico ingresa los encuentra desbloqueados.

**Comment by raulandresduque** [comment]
Ajustado, verificar

**Comment by julianjposadam** [comment]
Sigue desbloqueado después de cerrar la investigación.
