### ISSUE TITLE
247. Documental - Registro y exportar a Excel

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#241]
1. En el combo de tipo de documento arreglar porque dice "MANUALI" en lugar de "MANUAL"

2. Al exportar a Excel, en "Área o dependencia" y "Responsable" aparece el código y no la descripción. No  muestra "Fecha de aprobación" ni "Versión"

3. Si llegas a alcanzar, por favor cargas la información que te envío por correo para no tener que digitarla mañana

**Comment by raulandresduque** [comment]
1. OK
2. OK
3. En documentos no hay opción de cargue masivo, no alcanzo a hacer el cargue (que tenga multivalor en Area y Responsable complica hacerlo rápido)
