### ISSUE TITLE
248. Salud - Importación

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#242]
Te cuento que hice el cruce de información que tengo en Excel con la lista que me enviaste en el correo de la versión 44 y todos existen. Te envío por correo el archivo de Excel con el que hice la revisión.

Lo intenté cargar y me mostró error 2473; dice que no se ha encontrado la ruta de acceso. En la parte final dice "Actualizando accidentes" y abajo Fila 1, pero no avanza ni hace nada

**Comment by raulandresduque** [comment]
Se dan dos situaciones:
1. Hay exámenes del mismo empleado, fecha y empresa ... agregué que también valide el tipo de examen porque hay examen de retiro e ingreso en la misma fecha me imagino que cuando se renueva contrato
2. Hay un caso donde esta el mismo empleado, fecha, empresa y tipo de examen, esto para mi es un error (no se cargó ninguno de los registros y se genera un error cuando esta cargando). Revisa las filas 30 y 66 del excel veo que están con diferente proveedor, es posible?

Se hace cargo excepto del caso 2, habría que cargarlo manualmente.
