### ISSUE TITLE
249. Plan de acción - Formulario de registro

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#243]
En el formulario de registro de planes de trabajo (actividades) incluir dos campos de texto entre "Actividad o tarea" y "Observaciones". Se deben llamar "Resultado de las acciones" y "Resultado de la verificación". En el reporte de "No conformidades" existe un espacio para llevar lo que se haya registrado allí.

**Comment by raulandresduque** [comment]
Ajustado v0.47, validar
