### ISSUE TITLE
250. Accidentalidad - privilegios del administrador

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#244]
Quiero confirmar contigo si los privilegios del administrador relacionados con accidentalidad están bien, es el único que puede cerrar una investigación, y de requerirse, es el único que puede modificarla después de cerrada.

**Comment by raulandresduque** [comment]
No, esta algo diferente:
El administrador es el único que puede modificar un accidente cerrado.

**Comment by copgo** [comment]
¿Es muy demorado que aparte de lo que tiene, sea el único que pueda cerrar la investigación?

**Comment by copgo** [comment]
A propósito del tema de los accidentes cerrados, ¿hay como filtrar los cerrados?

**Comment by raulandresduque** [comment]
Ajustado v0.47, validar
