### ISSUE TITLE
251. Documental - lentitud en funcionamiento

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#245]
El comportamiento de este módulo (incluso antes de tener adjuntos) es demasiado lento y aunque nosotros ya lo habíamos detectado, hoy te lo escribo porque en la empresa nos dijeron que es poco práctico por la lentitud exagerada que tiene para hacer cualquier cosa

**Comment by raulandresduque** [comment]
Me funciona bien sin lentitud, por especificar justo en qué momento se vuelve lento

**Comment by copgo** [comment]
Todo el tiempo funciona lento, para abrir el formulario y registrar; para ver la consulta y moverse dentro de ella, en fin, todo lo hace en "cámara lenta" y realmente encuentro justa la queja del usuario, porque desespera hacer cualquier cosa en ese módulo

**Comment by raulandresduque** [comment]
En mi computador me funciona a una velocidad normal, lo que vi raro es que había un campo OLE como si el archivo quedara en la base de datos pero no vi código para eso pero en algunos campos tenia datos, muy extraño ... quite el campo e hice algunas pruebas y funciona bien.
Verificar en 0.47 la velocidad a ver si mejoró

**Comment by julianjposadam** [comment]
La velocidad en mi equipo no es mejor en comparación a los otros módulos. v0.48

**Comment by copgo** [comment]
Esperemos a probar en Manos para ver si mejoró la velocidad

**Comment by qpanzmbrainz** [comment]
Hoy lo probé en la empresa y sigue demasiado lento este módulo, por favor revisas qué otra cosa se podría hacer

**Comment by copgo** [comment]
Hoy lo probé en la empresa y sigue demasiado lento este módulo, por favor revisas qué otra cosa se podría hacer

**Comment by raulandresduque** [comment]
Sigo sin ver lentitud en el módulo de mi lado y no veo nada extraño a nivel de código ni de tabla:
1. Quité algunas listas de búsqueda probar si mejora la velocidad
2. Explicarme EXACTAMENTE cuándo se percibe la lentitud
3. Revisar desde runtime y desde access a ver si los tiempo son lentos en los dos casos

**Comment by julianjposadam** [comment]
La velocidad mejoró considerablemente lo que si se demora mucho es cuando se utiliza la búsqueda que se encuentra en la parte inferior de la consulta.

**Comment by raulandresduque** [comment]
Me imagino que se refiere a la búsqueda que hay entre los botones de desplazamiento de registro y la barra de desplazamiento horizontal, este tipo de búsqueda por naturaleza es lento ya que busca sobre TODO y no hay mucho que pueda hacer diferente a deshabilitarlo. La recomendación es que utilicen la búsqueda específica por campo en el rótulo de cada columna o si hay filtros comunes utilizar la opción de filtros favoritos.

**Comment by copgo** [comment]
Tuviste en cuenta lo que escribieron en el correo hoy, acerca de los adjuntos de este módulo?

**Comment by raulandresduque** [comment]
No se entiende muy bien, lo que entiendo es que después de editar un documento vuelve la lista la primero pero no veo cómo esto afecta el ingreso de información.

**Comment by julianjposadam** [comment]
Vamos a esperar a probarlo en la empresa

**Comment by raulandresduque** [comment]
Me lo asignas cuando tengas los comentarios
