### ISSUE TITLE
252. Accidentalidad - Incluir campo

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#246]
Por favor incluir un campo en el registro de accidentalidad que se llame "Investigación cerrada", la cual puede ser Si o No. En la consulta debe mostrar tanto los cerrados como los abiertos, pero el usuario puede filtrar si lo desea. En el ítem anterior, te decía que cerrarla o abrirla sólo son privilegios del administrador

**Comment by raulandresduque** [comment]
El campo ya existe pero no estaba incluido en la consulta, adicional se incluye un filtro predefinido
Validar v0.47

**Comment by copgo** [comment]
Aunque no he visto la versión 47, te aclaro que no quiero que al entrar a la consulta ya esté activo el filtro. Debe mostrar todas los registros pero el usuario si quiere los puede filtrar tanto en Access, como al exportar a Excel o  al hacer tabla dinámica

**Comment by raulandresduque** [comment]
Si, así quedó.
Validar en 0.47
