### ISSUE TITLE
253. Talento humano - Registro

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#247]
1. Cambiar "Talento humano" por "Gestión humana"
2. Colocar una casilla de verificación en el formulario de Selección que diga "Cerrada". Tener en cuenta incluir el mismo campo (Si/No) en el cargue masivo. En las salidas (consulta, exportar a Excel y tabla/gráfica dinámica) este campo debe quedar disponible.
3. Cuando se guarde una requisición en Selección, los campos "No. vacantes" y "Fecha planteada de entrega" deben quedar bloqueados para que no puedan ser modificados. Aplica tanto para cargue manual como masivo. Si no es muy dispendioso, dejar que el administrador si los pueda modificar.
4. En Contratación cambiar "Acción comunal" por "Red de empleo".
5. En Contratación cambiar "Tarjeta de la ANEC" por "Rethus"

**Comment by raulandresduque** [comment]
1. OK
2. OK, es el último campo en el archivo de cargue
3. OK
4. OK
5. OK

Validar v0.48

**Comment by julianjposadam** [comment]
1. Los títulos de la consulta de selección dicen Talento humano y debería decir Selección, en administrador de ususarios en permisos también sigue apareciendo Talento humano.
2. OK
3. OK
4. OK
5. OK

**Comment by raulandresduque** [comment]
Ajustado v0.49, validar

**Comment by julianjposadam** [comment]
El título de la pestaña de selección ya fue corregido, al igual que en administración de usuarios, pero el título principal de la consulta de selección sigue diciendo Talento humano.

**Comment by raulandresduque** [comment]
Ajustado v0.50, validar
