### ISSUE TITLE
254. Trabajador - Reporte para imprimir

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#248]
En el formulario de "Trabajador" colocar un botón que diga "Generar formato", el cual carga la información en el formato "GH-F-10 Novedad de ingreso" (enviado por correo electrónico)

**Comment by raulandresduque** [comment]
Implementado en v0.50, verificar

**Comment by julianjposadam** [comment]
El formato si es, pero si es posible ajustarla para que quede en una página.

**Comment by raulandresduque** [comment]
Al ver la vista preliminar para imprimir me aparece en una sola página

**Comment by copgo** [comment]
Julián me mostró el reporte y aparece en cuatro páginas

**Comment by raulandresduque** [comment]
Adjunto imágen de vista preliminar de excel, por favor verificar el tamaño de papel
![printscreen](https://cloud.githubusercontent.com/assets/1543644/17879593/ba76746a-68b8-11e6-942b-1b5d8b2b07d3.png)
