### ISSUE TITLE
255. Trabajador y Contratación - Ingreso de información

### ISSUE THREAD

**Issue by copgo** [raulandresduque/SGSST#249]
Como te expliqué por teléfono, la forma de ingresar la información del trabajador va a cambiar, quedando así el proceso:
1. Se ingresa la información del trabajador de forma manual en el formulario actual de "Trabajador". Al guardar, debe quedar el registro tanto en el módulo "Trabajador" (como está), como en el módulo "Gestión humana / Contratación".
2. Cuando se hagan las afiliaciones y la revisión de documentación, se ingresa por Contratación y a través de la consulta (vínculo) se abre el registro que se desea actualizar. Según esto, se debe retirar el botón "Nuevo" de Contratación.

Tener en cuenta las siguientes consideraciones:
1. Por cada registro de historia ocupacional se va a generar un registro en Contratación.
2. Todos los trabajadores se van a ingresar de forma manual por el formulario de "Trabajador"; el cargue masivo sólo se utilizará para actualizar retiros y cambios organizaciones.

**Comment by raulandresduque** [comment]
Implementado v0.50, validar.
Tener en cuenta que se crea al momento de crear una historia laboral no al crear un empleado.
El cargue automático quedó igual, al insertar una historia laborar se crea el registro en contratación

**Comment by julianjposadam** [comment]
Hace falta eliminar el botón de cargue masivo para contratación.

**Comment by raulandresduque** [comment]
Ajustado v0.52, validar
