### ISSUE TITLE
37. Accidentalidad - ¿La columna G 'Código' a qué se refiere?. 

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#27]
¿La columna G 'Código' a qué se refiere?.

**Comment by raulandresduque** [comment]
Id del accidente.

**Comment by julianjposadam** [comment]
La columna aún sigue y si es posible quitarla de la vista del usuario.

**Comment by raulandresduque** [comment]
Ajustado v0.31, validar
