### ISSUE TITLE
42. Accidentalidad - En el informe de accidentalidad exporta las funciones en inglés mostrando error (igual a observación 17 de trabajadores).

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#32]
En el informe de accidentalidad exporta las funciones en inglés mostrando error (igual a observación 17 de trabajadores).

**Comment by raulandresduque** [comment]
Como comenté en la observación #9 hice un código para que identifique el idioma, agregué a la barra de título una información sobre el idioma que detecta, por favor enviármelo para determinar si lo está identificando incorrectamente.

**Comment by julianjposadam** [comment]
El informe de trabajadores ya no muestra las funciones en inglés, mientras que el de accidentalidad sigue con el mismo problema.

**Comment by raulandresduque** [comment]
Ajustado v0.31, validar
