### ISSUE TITLE
45. Accidentalidad - En la consulta de accidentalidad no está mostrando todas las variables de la tabla.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#35]
En la consulta de accidentalidad no está mostrando todas las variables de la tabla.

**Comment by raulandresduque** [comment]
Agregué algunos campos de accidente pero este formulario esta MUY pesado y ya no deja trabajar sobre él, se bloquea y queda muy lento, lo ideal sería revisar la cantidad mínima de campos que requiere este formulario.
Los campos que son multivalor no se pueden agregar

**Comment by copgo** [comment]
Hola Andrés. La otra opción es dejar un formulario de accidente y otro de investigación, porque no es posible eliminar campos.
Mañana voy a empezar a usar la página que me dijiste.
Que estés bien,
Patricia

Enviado desde Yahoo Mail para Android 
 
  El dom, jun 5, PM a 10:40 PM, Raul Duque<notifications@github.com> escribió:   
Agregué algunos campos de accidente pero este formulario esta MUY pesado y ya no deja trabajar sobre él, se bloquea y queda muy lento, lo ideal sería revisar la cantidad mínima de campos que requiere este formulario.
Los campos que son multivalor no se pueden agregar

**Comment by raulandresduque** [comment]
Indicarme si falta algún campo (excepto los multivalor que no pueden adicionarse por restricciones técnicas).
