### ISSUE TITLE
48. Accidentalidad -  En indicadores sobran las cuatro gráficas inferiores. Eliminar la flecha con hipervínculo que pasa a la hoja de gráficas.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#38]
En indicadores sobran las cuatro gráficas inferiores. Eliminar la flecha con hipervínculo que pasa a la hoja de gráficas.

**Comment by raulandresduque** [comment]
Quite el hipervinculo pero no entiendo a cuales cuatro gráficas te refieres ya que son 6 gráficas distribuidas en 2 filas de 3 gráficas cada una ... se borran las gráficas de la 2da fila?

**Comment by copgo** [comment]
En la versión que revisé habían ocho gráficas distribuidas en dos filas: la fila de arriba tenía índice de frecuencia, índice de severidad, ILI y tasa de accidentalidad; estos son los que quedan. La fila de abajo tenía las variaciones de cada uno de estos; éstas se eliminan. Para todos los reportes de indicadores (de cualquier módulo) te pido que quites los hipervínculos y las flechas que dicen Gráficas, Volver o cualquier otra cosa, porque ese fue un formato que nos dio una empresa para otro trabajo y Diego la tomó igual. No quiero que se vean tan parecidas a lo de otra empresa.

**Comment by raulandresduque** [comment]
Se quitaron los vínculos, se dejó en cero los meses que no tengan datos, se agregó la gráfica AT que faltaba y se eliminaron las gráficas de variación
