### ISSUE TITLE
49. Ausentismo - Definir variables obligatorias

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#39]
Definir variables obligatorias

**Comment by raulandresduque** [comment]
Las variables obligatorias que están definidas en el cargue por pantalla son: Empresa, empleado, Fecha inicio, origen, CIE10.
Deje las mismas para el cargue masivo.

**Comment by julianjposadam** [comment]
Para guardar por formulario está bien, pero cuando se estaba importando un ausentismo al finalizar generó un error (2473) 

![errorausentismo](https://cloud.githubusercontent.com/assets/19801294/15910459/8555d0f4-2d90-11e6-87ab-c8fb7ca71570.jpg)

y no actualiza los registros.

**Comment by raulandresduque** [comment]
Por favor enviarme el archivo que se intentar cargar

**Comment by julianjposadam** [comment]
Sigue el mismo problema. Le envío el archivo excel con el cual he estado haciendo pruebas.
[Ausentismo.xlsx](https://github.com/raulandresduque/SGSST/files/335661/Ausentismo.xlsx)

**Comment by raulandresduque** [comment]
Envieme por favor el contenido del cuadro de texto donde se va visualizando el avance del proceso de importanción justo en el momento que sale el mensaje

**Comment by julianjposadam** [comment]
![cargue-ausentismo](https://cloud.githubusercontent.com/assets/19801294/16588311/1f40ed80-4294-11e6-8389-6c0e4822eea4.jpg)

**Comment by raulandresduque** [comment]
No he encontrado nada raro excepto que se genera un error cuando las fechas EPS y Reincorporación están vacías, lo ajuste para que queden vacias en este caso por favor validar. Si vuelve a fallar por favor enviar base de datos y archivo que se intenta cargar. Validar en v0.39
Adjunto ejemplo de archivo cargado
[Cargue Ausestismo.xlsx](https://github.com/raulandresduque/SGSST/files/349775/Cargue.Ausestismo.xlsx)
