### ISSUE TITLE
7. Administracion - Al dar permisos de usuario básico no habilita el módulo trabajador

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#4]
Al dar permisos de usuario básico no habilita el módulo trabajador

**Comment by raulandresduque** [comment]
[PC]No funciona ni en Access ni en runtime. 

[RD]Confírmame que lo estás haciendo con la misma DB que te envío y qué usuario estas usando porque no me pasa.

**Comment by raulandresduque** [comment]
Confírmame que lo estás haciendo con la misma DB que te envío y qué usuario estas usando porque no me pasa

**Comment by copgo** [comment]
El problema continúa. Lo hice con el usuario Prueba en la base de datos que me acabas de enviar

**Comment by raulandresduque** [comment]
Hola, hago al prueba ingresando con los dos usuarios básicos que hay en la DB (basico y usuprueba) y para los dos me muestra todas las opciones del menú trabajador.

Qué sucede exactamente? no parecen las opciones? aparecen deshabilitadas? da algún mensjae al intentar acceder a las opciones?
