### ISSUE TITLE
51. Ausentismo - La fecha de pago de la entidad social está mal validada, porque no puede ser menor a la fecha de inicio de incapacidad, ni mayor a la fecha actual.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#41]
La fecha de pago de la entidad social está mal validada, porque no puede ser menor a la fecha de inicio de incapacidad, ni mayor a la fecha actual.

**Comment by raulandresduque** [comment]
Ajustado en v.0.28, probar

**Comment by julianjposadam** [comment]
Sigue aceptando fechas anteriores a la de inicio y mayores a la actual.
