### ISSUE TITLE
14. Trabajador - Fecha final anterior a la inicial

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#5]
La fecha final se está cargando correctamente cuando se hace de forma masiva, pero al hacerlo manual puede generar error dejando una fecha final anterior a la inicial

**Comment by raulandresduque** [comment]
[RD]Por defecto la fecha queda en 31/12/9999, agregué la validación de Final > Inicial. 

[PC]No se pudo probar porque no dejó guardar la segunda historia ocupacional de un trabajador (o al menos no actualizó la consulta). Me guarda sin problemas envíame pantallazos de los datos que estas ingresando.

**Comment by raulandresduque** [comment]
Me guarda sin problemas envíame pantallazos de los datos que estas ingresando.

**Comment by copgo** [comment]
Hoy me funcionó bien pero aquí tengo Access; mañana lo pruebo en la oficina en la máquina virtual con runtime
