### ISSUE TITLE
60. condiciones de salud y de trabajo - En la cinta de opciones unir 'Administración salud' y 'Salidas Salud' en 'Salud'; y unir 'Administración PVE' y 'Salidas PVE' en 'PVE'. Quitar mayúscula a 'Matriz de Riesgos'.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#50]
En la cinta de opciones unir 'Administración salud' y 'Salidas Salud' en 'Salud'; y unir 'Administración PVE' y 'Salidas PVE' en 'PVE'. Quitar mayúscula a 'Matriz de Riesgos'.

**Comment by raulandresduque** [comment]
Ajustado v0.28, validar

**Comment by julianjposadam** [comment]
La etiqueta del grupo 'Matriz de Riesgos' sigue en mayúsculas al igual que el botón 'Controles por Riesgos'.

**Comment by raulandresduque** [comment]
Ajustado v0.29, validar
