### ISSUE TITLE
63. Salud - Validar el campo donde se digita la talla para que tenga decimal; es decir que si se digita un número entero le avise que la talla debe estar en metros y no en centímetros.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#53]
Validar el campo donde se digita la talla para que tenga decimal; es decir que si se digita un número entero le avise que la talla debe estar en metros y no en centímetros.

**Comment by raulandresduque** [comment]
Ajustado v0.28, validar

**Comment by julianjposadam** [comment]
Aparece el mensaje si se escribe un entero o un decimal y no deja continuar ni salir del formulario.

**Comment by raulandresduque** [comment]
Tener en cuenta el separador de decimales que tenga configurado el equipo ya sea coma o punto

**Comment by julianjposadam** [comment]
No funciona ni con punto y coma, ni coma, ni punto.

**Comment by raulandresduque** [comment]
No me reproduce. 
El mensaje es "Talla debe estar en metros" ?

**Comment by copgo** [comment]
A mí tampoco  me funcionó ni con punto ni con coma; independiente de cómo lo escriba, me muestra el mensaje

**Comment by raulandresduque** [comment]
Esta muy raro me funciona sin problema, agregué información adicional al mensaje de error por favor enviarme pantallas probando con punto y con coma

**Comment by julianjposadam** [comment]
Error con punto
![errorconpunto](https://cloud.githubusercontent.com/assets/19801294/16310908/fd1b3774-3933-11e6-8e90-764badf412c4.jpg)

Error con coma
![errorconcoma](https://cloud.githubusercontent.com/assets/19801294/16310970/3bcca58e-3934-11e6-9555-47aa4f1ccc9b.jpg)

**Comment by copgo** [comment]
En Manos también generó el error tanto con punto como con coma; para evitarlo se ingresará en centímetros, para ello: cambiar etiqueta a "Talla (cm)"; cambiar la validación para que admita números entre 100 y 215; en la fórmula de índice de masa corporal (IMC) dividir el valor de la talla en 100 para que pase a metros

**Comment by raulandresduque** [comment]
Ajustado v0.36, validar.
