### ISSUE TITLE
15. Trabajador - En el histórico no muestra todos los registros que tiene el trabajador

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#6]
La fecha final se está cargando correctamente cuando se hace de forma masiva, pero al hacerlo manual puede generar error dejando una fecha final anterior a la inicial

**Comment by raulandresduque** [comment]
[PC]Quedó sin probar por la misma razón que el anterior

**Comment by raulandresduque** [comment]
Volver a revisarlo por favor

**Comment by copgo** [comment]
Tengo dos trabajadores a los cuales les había cargado manualmente dos registros de historia ocupacional (cada uno tenía un cargo activo y uno inactivo). Luego cargué masivamente un cargo de cada uno y no dejó inactivo el anterior. El ejemplo era que la persona empezaba hoy a trabajar, por lo cual al cargo anterior debió haberle dejado que se retiraba el 31/05/2016 e inactivo; pero no lo hizo. Te voy a adjuntar la captura de pantalla

**Comment by copgo** [comment]
![importar trabajadores](https://cloud.githubusercontent.com/assets/19764263/15841958/acd090e6-2c1a-11e6-8439-f7d1ed04b61f.png)

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar
