### ISSUE TITLE
72. Salud - Al pedir el informe de salud para toda la empresa, no lo generó y mostró error: (Al hacer clic evento inesperado)

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#62]
Al pedir el informe de salud para toda la empresa, no lo generó y mostró error: (Al hacer clic evento inesperado)

**Comment by raulandresduque** [comment]
Creo que previamente había hecho algo, volver a validar

**Comment by julianjposadam** [comment]
continúa el error en la versión 0.30

**Comment by raulandresduque** [comment]
Me genera reporte en las dos situaciones: con o sin seleccionar empresa. Puede ser un tema de datos  (enviarme copia de la DB con la cual se genera el problema)

**Comment by julianjposadam** [comment]
Base de datos usada.
[SGSST.zip](https://github.com/raulandresduque/SGSST/files/318718/SGSST.zip)

**Comment by raulandresduque** [comment]
Probé con la Db que me envía y me genero el reporte pero sólo hay un registro, puede confirmar que el problema persiste. Exactamente qué es lo que pasa? hay error? no se muestra el excel? abre el excel pero vacio?

**Comment by julianjposadam** [comment]
Cuando se elige a una empresa sale el siguiente mensaje

![error_infome_salud](https://cloud.githubusercontent.com/assets/19801294/16312085/b6e94bc4-3938-11e6-8d77-78bcc4a32631.jpg)

**Comment by raulandresduque** [comment]
No tengo ese problema, me genera el reporte con/sin seleccionar empresa. El mensaje es de la versión 0.32 probar en la más actual

**Comment by julianjposadam** [comment]
El problema persiste si se elige una empresa o el rango de fechas cambia. v0.36

**Comment by copgo** [comment]
Si no se elige empresa genera el reporte pero no muestra las columnas de las gráficas en Excel

![image](https://cloud.githubusercontent.com/assets/19764263/17009038/964b2aba-4ebc-11e6-8fa5-9242377864ab.png)

Si se elige empresa no genera el informe y muestra el siguiente error

![image](https://cloud.githubusercontent.com/assets/19764263/17009045/af01944a-4ebc-11e6-841a-fe7562fe9a01.png)

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar

**Comment by copgo** [comment]
Si no se elige empresa, ya sale bien el informe, pero si se elige empresa sigue dando error

![image](https://cloud.githubusercontent.com/assets/19764263/17122597/71de1bd0-52a2-11e6-8273-7f3f14a04fbb.png)

**Comment by raulandresduque** [comment]
Lo que me doy cuenta es que tienes abierta la consulta de salud y enviaste el informe, en este caso falla porque se llega al limite de tablas que pueden estar abiertas, intenta generar sin que esté abierta la consulta de salud e indicar al usuario sobre esta situación.

**Comment by copgo** [comment]
Ya lo probé así y lo generó bien. Listo, lo escribiré en el instructivo
