### ISSUE TITLE
74. Profesiograma - En la consulta pide elegir una empresa, lo cual no es necesario.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#64]
En la consulta pide elegir una empresa, lo cual no es necesario.

**Comment by raulandresduque** [comment]
La pide para filtrar en la consulta sólo lo de esa empresa, similar a como sucede con empleados donde se filtran por una empresa pero Humberto lo hizo así y no sobre la misma pantalla de consulta, además no tiene opción de TODOS. Dejamos así o quieres hacer algún ajuste?

**Comment by copgo** [comment]
Por favor déjalo como trabajadores

**Comment by raulandresduque** [comment]
Ajustado v0.29, validar

**Comment by julianjposadam** [comment]
Sigue pidiendo la empresa para filtrar.

**Comment by raulandresduque** [comment]
Como se comentó anteriormente se dejó igual que en trabajadores donde se pide la empresa a filtrar pero esta también la opción de TODOS
