### ISSUE TITLE
76. Profesiograma - El campo 'Identificación del puesto de trabajo' no debe ser memo.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#66]
El campo 'Identificación del puesto de trabajo' no debe ser memo.

**Comment by raulandresduque** [comment]
Qué debe ser? un texto?
No tengo el requerimiento de este módulo

**Comment by copgo** [comment]
Si, debe ser texto libre (pero corto)

**Comment by raulandresduque** [comment]
Ajustado v0.29, validar
