### ISSUE TITLE
77. Profesiograma - Arreglar diseño del formulario. Quitar mayúsculas innecesarias (en segundas palabras y sostenidas).

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#67]
Arreglar diseño del formulario. Quitar mayúsculas innecesarias (en segundas palabras y sostenidas).

**Comment by raulandresduque** [comment]
Ajustado v0.29, verfificar

**Comment by julianjposadam** [comment]
En la segunda pestaña dice "FUNCIONES", también hay que quitarle las mayúsculas sostenidas.

**Comment by raulandresduque** [comment]
Ajustado v0.31, validar
