### ISSUE TITLE
17. Trabajador - Al importar dos trabajadores lo hizo correctamente, pero al finalizar salió un error. 

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#7]
Al importar dos trabajadores lo hizo correctamente, pero al finalizar salió un error

**Comment by raulandresduque** [comment]
[PC] Ya no sale el error, pero al cargar un nuevo cargo a un trabajador, dejó los dos registros activos y no colocó la fecha final como dice en los requerimientos.

**Comment by raulandresduque** [comment]
Ajustado, volver aprobar

**Comment by julianjposadam** [comment]
Al cargar un nuevo cargo persiste el error de no cambiar la fecha, además la herramienta se cierra repentinamente al querer ingresar a algún registro histórico ocupacional.

**Comment by julianjposadam** [comment]
Al importar un trabajador sin todos los campos continua validando datos que no son obligatorios. (Raza, tipo salario, frecuencia pago, tipo vinculación.

**Comment by raulandresduque** [comment]
Julian, por favor enviame el archivo que intentas cargar

**Comment by julianjposadam** [comment]
[Trabajadores - copia 2.xlsx](https://github.com/raulandresduque/SGSST/files/304896/Trabajadores.-.copia.2.xlsx)

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar
