### ISSUE TITLE
85. EPP - En el formulario los EPP no coindicen con los guardados en el módulo Administración/Matriz de riesgos y epp para cada cargo, sino que aparecen todos. Creo que lo mejor es insertar una columna entre 'Elemento' y 'Entregado' que se llame 'Requerido', para que aparezcan con 'Si' los que se marcaron en la matriz de riesgos y epp.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#75]
En el formulario los EPP no coindicen con los guardados en el módulo Administración/Matriz de riesgos y epp para cada cargo, sino que aparecen todos. Creo que lo mejor es insertar una columna entre 'Elemento' y 'Entregado' que se llame 'Requerido', para que aparezcan con 'Si' los que se marcaron en la matriz de riesgos y epp.

**Comment by raulandresduque** [comment]
Tenia un error pero como funciona es que los EPP definidos en la matriz aparecen por defecto como entregados y el usuario decide si los deja o no o si adiciona otros nuevos

**Comment by julianjposadam** [comment]
De acuerdo.
