### ISSUE TITLE
86. EPP - En el formato que se exporta en Word para imprimir, coloca los valores que se entregaron de la dotación a otros elementos, por ejemplo, marcamos 'Tapaoídos' y apareció en 'Vestido de oficina' y lo de 'Casco' apareció en 'Gafas claras'.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#76]
En el formato que se exporta en Word para imprimir, coloca los valores que se entregaron de la dotación a otros elementos, por ejemplo, marcamos 'Tapaoídos' y apareció en 'Vestido de oficina' y lo de 'Casco' apareció en 'Gafas claras'.

**Comment by raulandresduque** [comment]
Ajustado v0.29, verificar

**Comment by julianjposadam** [comment]
En el formato aparece NA siempre al lado del elemento aún habiendo marcado con SI varios elementos.

**Comment by raulandresduque** [comment]
Julián,

Creo que me estás asignando los casos que vas a cerrar, debes es darle CLOSE ISSSUE.

Raúl duque

**Comment by raulandresduque** [comment]
Validar

**Comment by julianjposadam** [comment]
En el formato no está colocando Si a los entregados y la fecha está muy clara. 
[EPP_17945704 DEIBER MANUEL GONZALEZ PEREZ_20160621_161335.pdf](https://github.com/raulandresduque/SGSST/files/326618/EPP_17945704.DEIBER.MANUEL.GONZALEZ.PEREZ_20160621_161335.pdf)

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar
