### ISSUE TITLE
87. No conformidad - Mejorar el diseño del formulario.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#77]
Mejorar el diseño del formulario.

**Comment by raulandresduque** [comment]
Ajustado v0.29, validar

**Comment by julianjposadam** [comment]
Alinear "Descripción del Hallazgo" junto con las otras etiquetas y quitar la mayúscula  a "Hallazgo", de igual forma alinear "Impacto" con las otras etiquetas.

**Comment by raulandresduque** [comment]
Ajustado v0.31, validar
