### ISSUE TITLE
18. Trabajador - Definir variables obligatorias

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#8]
Definir variables obligatorias

**Comment by raulandresduque** [comment]
[PC] Estas son las que valida en el cargue manual por formulario, pero no en el cargue masivo; ahí es cuando pide todas para poder importar la información

**Comment by raulandresduque** [comment]
Ajuste los campos obligatorios a los mismos que están en el cargue por formulario

**Comment by julianjposadam** [comment]
Para el cague masivo pide como dato obligatorio la raza mientras que en el cargue manual no lo es.

**Comment by julianjposadam** [comment]
En la versión 0.32 pide como obligatorio la raza y el estrato al momento de importar, y en la forma manual no lo hace.

**Comment by raulandresduque** [comment]
Ajustado v0.33, validar

**Comment by julianjposadam** [comment]
La validación ya es correcta, pero no inserta ningún registro.

**Comment by raulandresduque** [comment]
Ajustado v0.36, validar.
