### ISSUE TITLE
91. No conformidad - El botón de verificación 'Plan de acción' no despliega el formulario para diligenciarlo.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#81]
El botón de verificación 'Plan de acción' no despliega el formulario para diligenciarlo.

**Comment by raulandresduque** [comment]
Se tuvo que replantear esto ya que no estaba implementando el esquema que tienen los otros módulos para Plan de Acción, quedó como en los otros módulos. Verificar en v0.29

**Comment by julianjposadam** [comment]
No se pudo verificar bien el funcionamiento, ya que no esta guardando ninguna no conformidad.

**Comment by raulandresduque** [comment]
Ajustado v0.31, validar
