### ISSUE TITLE
97. No conformidad - En la gráfica del indicador dejar los nombres de los meses abreviados con tres letras.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#87]
En la gráfica del indicador dejar los nombres de los meses abreviados con tres letras.

**Comment by raulandresduque** [comment]
Ajustado v0.30, validar

**Comment by julianjposadam** [comment]
Sigue igual.

**Comment by raulandresduque** [comment]
Confirmé y si está modificado, por favor reconfirmar que la base de datos sea la última ya que las plantillas se almacenan en la base de datos

**Comment by julianjposadam** [comment]
La base de datos que se usan para las pruebas es la última versión.
