### ISSUE TITLE
99. No conformidad -  La plantilla de indicadores dice en el título indicadores de ausentismo y es indicador de no conformidad.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#89]
La plantilla de indicadores dice en el título indicadores de ausentismo y es indicador de no conformidad.

**Comment by raulandresduque** [comment]
Ajustado v0.30, validar

**Comment by julianjposadam** [comment]
Sigue saliendo

**Comment by raulandresduque** [comment]
Confirmé y si está modificado, por favor reconfirmar que la base de datos sea la última ya que las plantillas se almacenan en la base de datos
