### ISSUE TITLE
19. En el informe sociodemográfico exporta las funciones en inglés mostrando error

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#9]
En el informe sociodemográfico exporta las funciones en inglés mostrando error

**Comment by raulandresduque** [comment]
[PC] Sigue presentando el mismo error

**Comment by raulandresduque** [comment]
Hice algo “complicado” para que detecte el idioma que tiene office, por favor envíame TODOS los pantallazos que aparecen la primera vez que se abre la aplicación porque aquí es donde identifica esto.

**Comment by copgo** [comment]
Sigue igual. Mañana cuando descargue la última versión de la herramienta en la oficina, tomo las capturas de pantalla y te las envío

**Comment by copgo** [comment]
Te envío tres adjuntos: los dos primeros son los mensajes que salen al abrir la herramienta sin haberla vinculado a la base de datos (versión 28) y el tercero es la parte de arriba de la ventana de Access para que veas que dice que está en inglés
![office ingles](https://cloud.githubusercontent.com/assets/19764263/15867067/128d0446-2ca7-11e6-9b8f-e3e2f47d1e11.png)
![mensaje inicial 2](https://cloud.githubusercontent.com/assets/19764263/15867068/128ef5ee-2ca7-11e6-9e93-2ce0b9bf4d0b.png)
![mensaje inicial 1](https://cloud.githubusercontent.com/assets/19764263/15867069/12930fe4-2ca7-11e6-8396-ef0ad322c5d3.png)

**Comment by julianjposadam** [comment]
No genera el informe aun habiendo registros.

**Comment by raulandresduque** [comment]
Julian, es extraño que no me esté encontrando la versión del office según la imágen. Usted me ayuda confirmando la carpeta EXACTA donde está el excel/word ... las rutas que estoy considerando son:
C:\Program Files\Microsoft Office\Office14\
C:\Program Files (x86)\Microsoft Office\Office14\
C:\Program Files\Microsoft Office\Office15\
C:\Program Files (x86)\Microsoft Office\Office15\
C:\Archivos de programa\Microsoft Office\Office14\
C:\Archivos de programa (x86)\Microsoft Office\Office14\
C:\Archivos de programa\Microsoft Office\Office15\
C:\Archivos de programa (x86)\Microsoft Office\Office15\
