### ISSUE TITLE
103. Documental - Quitar mayúsculas innecesarias (segundas palabras).

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#93]
Quitar mayúsculas innecesarias (segundas palabras).

**Comment by raulandresduque** [comment]
Ajustado v0.30, validar

**Comment by julianjposadam** [comment]
Falta corregir ""Tipo de Documento", "Documento Externo" (dentro de la lista) y "Nombre del Documento"

**Comment by raulandresduque** [comment]
Ajustado v0.31, validar
