### ISSUE TITLE
108. No conformidad - El formulario de indicadores dice 'No conformidades'. Dice indicadores pero sólo es un indicador.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#98]
El formulario de indicadores dice 'No conformidades'. Dice indicadores pero sólo es un indicador.

**Comment by raulandresduque** [comment]
Ajustado v0.30, validar

**Comment by julianjposadam** [comment]
El archivo de excel aún no esta corregido.

**Comment by raulandresduque** [comment]
Tanto el título en la barra de la ventana como el título en el encabezado del formulario fue modificado a "indicador", por favor enviar un pantallazo exactamente donde no se esta viendo correctamente.

**Comment by julianjposadam** [comment]
![indicador_noconformidad](https://cloud.githubusercontent.com/assets/19801294/16122681/9ee82c7e-33ad-11e6-8eb6-90d53de2a11a.jpg)
Además estandarizar el formulario para que quede en singular los títulos. 
![formulario_noconformidad](https://cloud.githubusercontent.com/assets/19801294/16122736/dd6324cc-33ad-11e6-8e69-fa589cdfd810.jpg)

**Comment by raulandresduque** [comment]
No comprendo donde se esta reportando el error ... es en Documental o en No conformidad ?

**Comment by julianjposadam** [comment]
Que pena es en No conformidad.

**Comment by raulandresduque** [comment]
Ajustado v0.35, validar

**Comment by julianjposadam** [comment]
Los datos del archivo de excel no concuerdan con los registrados en la herramienta, tengo cuatro registros de enero a febrero, pero al momento de mostrar el excel me aparecen sólo enero y febrero. 
Falta corregir el título del archivo así como al encabezado de la hoja donde se encuentra la gráfica.

**Comment by raulandresduque** [comment]
Ajustado v0.37, validar

**Comment by copgo** [comment]
Corregir el título del formulario donde se especifican los parámetros del indicador, porque le falta la d final

![image](https://cloud.githubusercontent.com/assets/19764263/17009275/c192eca6-4ebe-11e6-884e-8b33fca51392.png)

**Comment by raulandresduque** [comment]
Ajustado v0.42, validar
