### ISSUE TITLE
109. Documental - En el botón de indicadores se está usando la plantilla de no conformidades, no se encuentra la especificada en los requerimientos.

### ISSUE THREAD

**Issue by raulandresduque** [raulandresduque/SGSST#99]
En el botón de indicadores se está usando la plantilla de no conformidades, no se encuentra la especificada en los requerimientos.

**Comment by raulandresduque** [comment]
Ajustado v0.30, verificar

**Comment by julianjposadam** [comment]
Sigue igual.

**Comment by raulandresduque** [comment]
Ajustado v0.34, validar

**Comment by julianjposadam** [comment]
Ajustar la etiqueta del eje X con los meses abreviados como las demás gráficas.

**Comment by raulandresduque** [comment]
Ajustado v0.35, validar
